### ISSUE TITLE
Missing WindowsStore as a supported OS (?)

### ISSUE THREAD

**Issue by William-Froelich** [conan-io/cmake-conan#107]
I'm following instructions from: https://github.com/conan-io/conan/issues/1155

When using the configuration specified and conan.cmake, the build will halt and fail. 

```
Error output:
-- Conan ** WARNING** : This detection of settings from cmake is experimental and incomplete. Please check 'conan.cmake' and contribute
CMake Error at build.win/conan.cmake:102 (message):
  cmake system WindowsStore is not supported by conan.  Use one of
  Windows;Linux;Macos;Android;iOS;FreeBSD
Call Stack (most recent call first):
  build.win/conan.cmake:407 (conan_cmake_settings)
  CMakeLists.txt:79 (conan_cmake_run)

-- Configuring incomplete, errors occurred!
```

Modifying conan.cmake to include WindowsStore as a supported OS  allows the build to complete successfully, but is this a miss in the supported OS list or are the instructions wrong on the linked issue?

**Comment by memsharded** [comment]
Closed by #109
