### ISSUE TITLE
conan_add_remote() requires conan_check()

### ISSUE THREAD

**Issue by db4** [conan-io/cmake-conan#108]
`conan` exe is run inconsistently across `conan.cmake`. `conan_cmake_install()`  uses `conan` from system PATH by default:
https://github.com/conan-io/cmake-conan/blob/c0258fce782597a6ef64050e2e67846598d27536/conan.cmake#L268 https://github.com/conan-io/cmake-conan/blob/c0258fce782597a6ef64050e2e67846598d27536/conan.cmake#L285-L289 https://github.com/conan-io/cmake-conan/blob/c0258fce782597a6ef64050e2e67846598d27536/conan.cmake#L334-L336
but `conan_add_remote()` requires `conan_check()` to find it first:
https://github.com/conan-io/cmake-conan/blob/c0258fce782597a6ef64050e2e67846598d27536/conan.cmake#L437 https://github.com/conan-io/cmake-conan/blob/c0258fce782597a6ef64050e2e67846598d27536/conan.cmake#L446 https://github.com/conan-io/cmake-conan/blob/c0258fce782597a6ef64050e2e67846598d27536/conan.cmake#L464 https://github.com/conan-io/cmake-conan/blob/c0258fce782597a6ef64050e2e67846598d27536/conan.cmake#L478-L479 Without `conan_check()`  variable `CONAN_CMD` does not exist and cmake function `execute_process()` (and thus macro `conan_add_remote()`) silently fails. No error message is shown, cmake continues execution.
I think that
1)  We somehow should check if `execute_process()` has been succeeded.  On my system  (python 3.7 windows x64)  if I add `RESULT_VARIABLE res` to `execute_process()` parameters, it returns `The system cannot find the file specified` in `res` on failure. But I don't know how to get numeric exit code from `execute_process()` to test if it's non-zero. Any idea?
2) All functions have to use `${CONAN_CMD}` by default that probably should be set by `find_program(CONAN_CMD conan)` at the very beginning.

**Comment by promgamer** [comment]
Hi,

Just came across this issue. I totally agree with 
> All functions have to use ${CONAN_CMD} by default that probably should be set by find_program(CONAN_CMD conan) at the very beginning.

Can I propose a PR to fix it? I think it can be as simple as doing a `conan_check` inside the `conan_add_remote()`

**Comment by promgamer** [comment]
I won't have time to pick this in November :disappointed: maybe December. Still need to tackle mongo-cxx-driver in my queue.

**Comment by db4** [comment]
@promgamer I'm just curious, what are you going to do with `mongo-cxx-driver`?

**Comment by promgamer** [comment]
@db4 https://github.com/bincrafters/conan-mongo-cxx-driver/tree/testing/3.3.0

**Comment by rddesmond** [comment]
I just created PR #146 which does 2/3 on memsharded's list (calls conan_check in other calls), I didn't add additional arguments to the add remotes command or setup the macros to do version checking (I figure that if you want that, it's just as easy to call conan_check manually).

**Comment by memsharded** [comment]
This has been mostly resolved by https://github.com/conan-io/cmake-conan/pull/146 (thanks @rddesmond ), so I am closing this. If there is some further detail that you still are interested in, like additional arguments, please open a new issue for it. Thanks!
