### ISSUE TITLE
Wrong initial working directory

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/cmake-conan#11]
Hi,

I get this error when trying to generate a Visual Studio project via cmake-gui:

```
PROJECT: 
Generated cmake created conanbuildinfo.cmake

PROJECT: 
ERROR: Generator cmake(file:conanbuildinfo.cmake) failed
[Errno 13] Permission denied: 'C:\\Program Files\\CMake\\bin\\conanbuildinfo.cmake'

PROJECT: 
Generated cmake_multi created conanbuildinfo_multi.cmake

PROJECT: 
ERROR: Generator cmake_multi(file:None) failed
[Errno 13] Permission denied: 'C:\\Program Files\\CMake\\bin\\conanbuildinfo_multi.cmake'
```

Looks like `conan.cmake` runs `conan install` in the current working directory, instead of in the generator output directory.

**Comment by memsharded** [comment]
Yes, that was true, we assumed that cmake was always running in the current binary directory, but that is not the case when using the cmake-gui. Thanks for fixing this!
