### ISSUE TITLE
Readme.md CMAKE_BINAR_DIR -> CMAKE_BINARY_DIR

### ISSUE THREAD

**Issue by bigla** [conan-io/cmake-conan#115]
Hi Devs!
Great Project!

In README.md : I suppose in Section "Creating packages"
    include(${CMAKE_BINAR_DIR}/conanbuildinfo.cmake)
should mean
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)

Not sure if opening an issue for this is OK. I'd like to ask for feedback if it is not.
Best Regards

**Comment by memsharded** [comment]
Hi @bigla 

Thanks for your kind words :)

Yes, definitely a typo. It is totally ok to open an issue for this. Also, if you want to directly submit a pull-request to fix it, that would be easy to do, and very appreciated.

Cheers!
