### ISSUE TITLE
Add support for Visual Studio 2019 (currently in preview)

### ISSUE THREAD

**Issue by tim-weis** [conan-io/cmake-conan#116]
Visual Studio 2019 (Preview) comes with improved CMake support. Unfortunately, cmake-conan doesn't recognize it's compiler (details in conan-io/conan#4146). Added support for Visual Studio 2019 (Preview) would be much appreciated.

**Comment by kmkim85** [comment]
Official one is now released

**Comment by MarcelRaad** [comment]
There's the third PR with exactly the same change now: https://github.com/conan-io/cmake-conan/pull/117, https://github.com/conan-io/cmake-conan/pull/139, https://github.com/conan-io/cmake-conan/pull/144. Could one of them be merged please?
