### ISSUE TITLE
Detection of clang >= 8.0 is wrong on mac

### ISSUE THREAD

**Issue by codeFabio** [conan-io/cmake-conan#122]
On Mac this script does not do the adjustment for non apple tip of development clang version number:

https://github.com/conan-io/cmake-conan/blob/5da19c4eb42b9c4f70af8f9b75ecf4fe1f7ca0f7/conan.cmake#L150

This branch needs the same adjustment to only use major version number as below (L157)

**Comment by memsharded** [comment]
This has been in theory closed by #118 

Will be in release 0.14
