### ISSUE TITLE
So conan picks up Composable profiles   ... does cmake-conan?

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/cmake-conan#125]
I tried: (notice two profiles)

conan_cmake_run(PROFILE
						MSVS15-ADT-release.txt
						MSVS15-ADT-Engage-release.txt
					BUILD_TYPE "Release"
					REQUIRES
						Qwt/6.1.3@adt/stable
					IMPORTS
						${CONANIMPORTS}
					BASIC_SETUP	CMAKE_TARGETS
					)

and it appears to hang

**Comment by memsharded** [comment]
Yes, conan-cmake doesn't support multi-profile yet. Submitted PR #126 for it, for next 0.14 cmake-conan release, thanks for raising the issue!
