### ISSUE TITLE
generates excessive library directories paths including directories that don't exist

### ISSUE THREAD

**Issue by Cyberdr8gon** [conan-io/cmake-conan#130]
We have been using cmake-conan in our [project](https://bitbucket.org/avslab/basilisk) and have come across a problem on MacOS with Xcode where we see warnings for attempting to link to PATHS that don't exist.

An example error:
`ld: warning: directory not found for option ‘-L/Users/thibaudteil/.conan/data/opencv/3.4.5/conan/stable/package/8cb67aa8aca987bb2ebfa7814003995d7aaf8388/lib/Debug’`

However, the actual directory is:
`/Users/thibaudteil/.conan/data/opencv/3.4.5/conan/stable/package/8cb67aa8aca987bb2ebfa7814003995d7aaf8388/lib`

The interesting thing is that the program runs and correctly find the right lib directory, it just seems that this superfluous linker path is added for some reason. We cannot find it in the conanbuildinfo.txt, thus we think either  conan/conanbuildinfo.cmake or cmake-conan is doing something strange.

Let me know if there is anything else I can provide to help resolve this issue.

**Comment by memsharded** [comment]
Hi @Cyberdr8gon 

I think this issue is not related to ``cmake-conan``, but to the conan client. I guess the problem is the same even if you call ``conan install`` directly from your terminal and not using cmake-conan, isn't it?

In that case the issue should be moved to the other repo (just tell me, I can transfer it automatically).

That issue sounds like some of your dependencies is using ``multi-config`` definitions in ``package_info()``, kind of:

```python
def package_info(self):
     self.cpp_info.debug.includedirs = ["include_debug"]
```

Are you using the OpenCV recipe from conan-center? Also which Conan generator are you using to build, ``xcode``? Or ``cmake``? Thanks for the feedback.

**Comment by Cyberdr8gon** [comment]
Thanks for the quick response. Yes, you are correct about it happening if one calls conan install directly. 

If you would like to transfer the issue that is fine by me!

We are using the OpenCV recipe from conan-center, and we use the cmake conan generator I believe.

**Comment by richjohnson-wwt** [comment]
I am seeing this for the CLI11 and fakeit dependencies which I believe are header-only and I do not see the unneeded lib directories at this location yet I get the warning:

ld: warning: directory not found for option '-L/Users/johnsori/.conan2/p/cli11328f4586e88b7/p/lib'
ld: warning: directory not found for option '-L/Users/johnsori/.conan2/p/fakeica2d0fe781f88/p/lib'

**Comment by memsharded** [comment]
Hi @richjohnson-wwt 

This was a quite old issue, and not really related to cmake-conan, but to recipes in ConanCenter.

It seems those 2 recipes from ConanCenter haven't properly removed ``libdirs``, as expected. I am closing this issue as solved, and I'd encourage to submit a ticket (or even better, a PR) to the ConanCenter github repo (like in https://github.com/conan-io/conan-center-index/blob/master/recipes/cli11/all/conanfile.py) to make sure ``self.cpp_info.libdirs = []`` and ``self.cpp_info.bindirs = []``.

Many thanks for your feedback!
