### ISSUE TITLE
Add wrapper for conan user command

### ISSUE THREAD

**Issue by bvnp43** [conan-io/cmake-conan#142]
will be good to have wrapper for this

```
execute_process(COMMAND conan user foo -p bar -r test_remote)
```

**Comment by memsharded** [comment]
Hi @bvnp43 

the only problem with this is that it will expose the password of the remote, in plain text, in the build scripts that are usually very visible. I am not sure this would be a recommended functionality at all.

There are environment variables (per remote), that will do the authentication automatically when necessary, those can be directly setup by cmake code if necessary (still the password will be there in plain text). Are you aware of them? have you tried using them? 

- https://docs.conan.io/en/latest/reference/env_vars.html#conan-login-username-conan-login-username-remote-name
- https://docs.conan.io/en/latest/reference/env_vars.html#conan-password-conan-password-remote-name

**Comment by bvnp43** [comment]
@memsharded Hi, didn't know those variables exist, probably need to better look into the docs, thanks much for the help.

**Comment by memsharded** [comment]
No problem, don't be afraid to ask any further question, glad to help!
