### ISSUE TITLE
Conan install fails in Visual Studio

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/cmake-conan#148]
I wanted to give `cmake-conan` a try using Visual Studio 2019.  I've included the following snippet towards the top of my main `CMakeLists.txt` file:

```cmake
configure_file(
  ${CMAKE_SOURCE_DIR}/conan.cmake
  ${CMAKE_BINARY_DIR}/conan.cmake
  COPYONLY)
include(${CMAKE_BINARY_DIR}/conan.cmake)
conan_cmake_run(
  CONANFILE conanfile.txt
  BASIC_SETUP CMAKE_TARGETS # conan_basic_setup(TARGETS)
  BUILD missing)
```

Visual Studio complains that it cannot find Conan, yet I can run Conan from the Powershell and CMD command-lines:

```
1> CMake generation started for configuration: 'x64-Debug'.
1> Found and using vcpkg toolchain file (C:/Users/woute/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\woute\source\repos\hdt2\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/HostX64/x64/cl.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.21.27702/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="C:/Users/woute/vcpkg/scripts/buildsystems/vcpkg.cmake" "C:\Users\woute\source\repos\hdt2"
1> Working directory: C:\Users\woute\source\repos\hdt2\out\build\x64-Debug
1> [CMake] -- Conan: Automatic detection of conan settings from cmake
1> [CMake] -- Conan: Detected VS runtime: MDd
1> [CMake] -- Conan: Settings= -s;arch=x86_64;-s;build_type=Debug;-s;compiler=Visual Studio;-s;compiler.version=16;-s;compiler.runtime=MDd
1> [CMake] -- Conan executing: conan install . -s arch=x86_64 -s build_type=Debug -s compiler=Visual Studio -s compiler.version=16 -s compiler.runtime=MDd -g=cmake --build=missing
1> [CMake] CMake Error at out/build/x64-Debug/conan.cmake:399 (message):
1> [CMake]   Conan install failed='The system cannot find the file specified'
```

Any ideas on what could be wrong here?

**Comment by wouterbeek** [comment]
I found a workaround for others who encounter this issue in the future: run Conan install from within Powershell:

```
${PROJECT_DIR}\out\build\x64-Debug> conan install ../../..
```

And then reload the project in Visual Studio.

**Comment by memsharded** [comment]
Hi @wouterbeek 

Not sure what could be failing. 

I think it could be because of running from the Microsoft Visual Studio embedded CMake, that might define different path or something. It would be useful if you could try launching directly from command line CMake, and what if you configure Visual Studio to use the system CMake instead of the bundled one, to try to know the reasons. Another possible thing to try is printing the PATH env-var from your CMakeList.txt and compare with the one from your command line where it works.

Please let me know, thanks!

**Comment by wouterbeek** [comment]
I no longer observe the above behavior.  I'm assuming it got solved by an intermediate update to the VS CMake version.

**Comment by memsharded** [comment]
Good @wouterbeek thanks for following up and closing. Please re-open if it appears again.
