### ISSUE TITLE
Detect Intel compiler on Linux

### ISSUE THREAD

**Issue by bl4ckb0ne** [conan-io/cmake-conan#166]
Hi, I'm using the `conan.cmake` file with the Intel compiler (11.1, 16.0 & 19), and none of them are detected by `conan_cmake_settings`.

`${CMAKE_${LANGUAGE}_COMPILER_ID}` evaluated to `Intel` and falls into the `else` statements with the following error :

```
CMake Error at /root/work/MR/build-system/conan.cmake:207 (message):
  Conan: compiler setup not recognized
Call Stack (most recent call first):
  /root/work/MR/build-system/conan.cmake:485 (conan_cmake_settings)
```

I'm using the release 0.14.

I will work on a fix from my side, would you be interested in having it upstream ?

**Comment by memsharded** [comment]
Hi @Bl4ckb0ne 

Well, the first thing is that Conan client itself doesn't have intel in the default settings.yml. It has been requested today too: https://github.com/conan-io/conan/issues/5590, so I think this will make sense after that one is solved. 

Thanks very much for your offer to help, please follow that issue and lets talk again when closed.

**Comment by Bl4ckb0ne** [comment]
We're using a custon `settings.yml`, which refers to the intel compiler as `icc`

```yml
compiler:
    icc:
        version: ["11.1", "16.0", "19.0"]
```

I have a quick fix for `conan.cmake` to detect `Intel`, but it fails later on in the `conanbuildinfo.cmake`.

I asked on the #conan channel in the cpplang slack, and I've been told to use `CONAN_DISABLE_CHECK_COMPILER`, which seems to work for now.

Here's my fix

```diff
diff --git a/conan.cmake b/conan.cmake
index aac3b9c..a9eb85d 100644
--- a/conan.cmake
+++ b/conan.cmake
@@ -139,6 +139,18 @@ function(conan_cmake_settings result)
             conan_cmake_detect_unix_libcxx(_LIBCXX)
             set(_CONAN_SETTING_COMPILER_LIBCXX ${_LIBCXX})
         endif ()
+    # Temp fix due to https://github.com/conan-io/cmake-conan/issues/166
+    elseif (${CMAKE_${LANGUAGE}_COMPILER_ID} STREQUAL Intel)
+        string(REPLACE "." ";" VERSION_LIST ${CMAKE_${LANGUAGE}_COMPILER_VERSION})
+        list(GET VERSION_LIST 0 MAJOR)
+        list(GET VERSION_LIST 1 MINOR)
+        set(COMPILER_VERSION ${MAJOR}.${MINOR})
+        set(_CONAN_SETTING_COMPILER icc)
+        set(_CONAN_SETTING_COMPILER_VERSION ${COMPILER_VERSION})
+        if (USING_CXX)
+            conan_cmake_detect_unix_libcxx(_LIBCXX)
+            set(_CONAN_SETTING_COMPILER_LIBCXX ${_LIBCXX})
+        endif ()
     elseif (${CMAKE_${LANGUAGE}_COMPILER_ID} STREQUAL AppleClang)
         # using AppleClang
         string(REPLACE "." ";" VERSION_LIST ${CMAKE_${LANGUAGE}_COMPILER_VERSION})

**Comment by memsharded** [comment]
Ok, good, seems harmless to conan.cmake, you can submit a PR, thanks!

**Comment by kapare** [comment]
@memsharded `conan` is now supporting intel since 1.21 
https://blog.conan.io/2019/12/16/New-conan-release-1-21.html
Anything is required/blocking this from being merged?

**Comment by willadsen** [comment]
What's the status here - is a PR planned @bl4ckb0ne ? Or is there another proper way to get intel compiler support @memsharded ?

**Comment by bl4ckb0ne** [comment]
I dont use `conan` anymore, feel free to submit my patch as a pull request.

**Comment by czoido** [comment]
Closed by: https://github.com/conan-io/cmake-conan/pull/288
