### ISSUE TITLE
conan install from cmake not working

### ISSUE THREAD

**Issue by akshit-sharma** [conan-io/cmake-conan#188]
As explained on the [conan website](https://docs.conan.io/en/latest/howtos/cmake_launch.html), it is a work under testing. I believe to found be a bug while using the code from the website.

### Link to the repo with tag
**Not working code**: https://github.com/akshit-sharma/KeyDetector/tree/conancmakeissue
**Working code**: https://github.com/akshit-sharma/KeyDetector/tree/conancmakeworking

### Not working code
[CMakeLists.txt](https://github.com/akshit-sharma/KeyDetector/blob/conancmakeissue/CMakeLists.txt) from **not working code**, I using conan.cmake to build the conanfile.txt from cmake.
```
# Download automatically, you can also just copy the conan.cmake file
if(NOT EXISTS "${CMAKE_CURRENT_BINARY_DIR}/conan.cmake")
   message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
   file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/master/conan.cmake"
                  "${CMAKE_CURRENT_BINARY_DIR}/conan.cmake")
endif()
include(${CMAKE_CURRENT_BINARY_DIR}/conan.cmake)
conan_cmake_run(CONANFILE conanfile.txt
                BASIC_SETUP CMAKE_TARGETS
                BUILD missing)
```

To run the code, 
1. first make sure you checkout the right tag
   - `git fetch --all --tags --prune`
   - `git checkout tags/conancmakeissue -b conancmakeissue`
2. make a folder `build`
3. go inside `build`
4. run `cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..`
5. run `make`

On running it gives an error that `-lportaudio` is not found.
The full output is at the _end of the message_.

### Working Code
[CMakeLists.txt](https://github.com/akshit-sharma/KeyDetector/blob/conancmakeworking/CMakeLists.txt) from **working code**, I only changed the above lines of code to
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```
To run the code, 
1. first make sure you checkout the right tag
   - `git fetch --all --tags --prune`
   - `git checkout tags/conancmakeworking -b conancmakeworking`
2. make a folder `build`
3. go inside `build`
4. run `conan install .. --build missing`
5. run `cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..` 
6. run `make`.

This compiles correctly.

### Expected Output:
I believe both the cmake file should be compiled without errors.

### Output from not working cmake file
```
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Debug;-s;compiler=gcc;-s;compiler.version=8;-s;compiler.libcxx=libstdc++11
-- Conan executing: conan install /home/akshit/Projects/PianoKeyDetector/conanfile.txt -s build_type=Debug -s compiler=gcc -s compiler.version=8 -s compiler.libcxx=libstdc++11 -g=cmake --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    portaudio/v190600.20161030@bincrafters/stable from 'bincrafters' - Cache
Packages
    portaudio/v190600.20161030@bincrafters/stable:761432f3453a17c960259b5b2605153e3bcffd7d - Cache

portaudio/v190600.20161030@bincrafters/stable: Already installed!
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Library portaudio found /home/akshit/.conan/data/portaudio/v190600.20161030/bincrafters/stable/package/761432f3453a17c960259b5b2605153e3bcffd7d/lib/libportaudio.a
-- Library jack not found in package, might be system one
-- Library asound not found in package, might be system one
-- Library m not found in package, might be system one
-- Library pthread not found in package, might be system one
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /home/akshit/Projects/PianoKeyDetector/build
-- Conan: Compiler GCC>=5, checking major version 8
-- Conan: Checking correct version: 8
-- Configuring done
-- Generating done
-- Build files have been written to: /home/akshit/Projects/PianoKeyDetector/build
Scanning dependencies of target PianoKeyDetector
[ 50%] Building CXX object CMakeFiles/PianoKeyDetector.dir/src/main.cpp.o
[100%] Linking CXX executable bin/PianoKeyDetector
/usr/bin/ld: cannot find -lportaudio
collect2: error: ld returned 1 exit status
CMakeFiles/PianoKeyDetector.dir/build.make:83: recipe for target 'bin/PianoKeyDetector' failed
make[2]: *** [bin/PianoKeyDetector] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/PianoKeyDetector.dir/all' failed
make[1]: *** [CMakeFiles/PianoKeyDetector.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by czoido** [comment]
Hi @akshit-sharma,
Thanks for the detailed instructions to reproduce the issue.
The problem is that you are using the `CMAKE_TARGETS` argument for `BASIC_SETUP` but you are latter not using the targets in the CMakeLists. 
You could change 
`target_link_libraries(PianoKeyDetector PUBLIC ${CONAN_LIBS})`
to
`target_link_libraries(PianoKeyDetector PUBLIC CONAN_PKG::portaudio)`
or you can remove the `CMAKE_TARGETS` argument and use `${CONAN_LIBS}`
Hope this helps, please tell me if this solves the issue.

**Comment by akshit-sharma** [comment]
@czoido, thanks for the reply.
I can compile using `target_link_libraries(PianoKeyDetector PUBLIC CONAN_PKG::portaudio)`. It works using this method.

I tried removing `CMAKE_TARGETS` to use with `${CONAN_LIBS}`.
The code didn't compile with the later configuration.
My conan_cmake_run and target_link_libraries command were:
```
conan_cmake_run(CONANFILE conanfile.txt
                               BUILD missing)
```
and 
```
target_link_libraries(<target_name> PUBLIC ${CONAN_LIBS})
```

Am I missing something for the later case?

**Comment by czoido** [comment]
Hi @akshit-sharma,
The problem here is that you have removed `BASIC_SETUP` and you just have to remove the `CMAKE_TARGETS` argument and leave `BASIC_SETUP`. Si like this:

```
conan_cmake_run(CONANFILE conanfile.txt
                BASIC_SETUP
                BUILD missing)
```
It should work. Hope this helps :)

**Comment by akshit-sharma** [comment]
It works. Thanks for the help.
