### ISSUE TITLE
compiler options relative to .conan despite INSTALL_FOLDER

### ISSUE THREAD

**Issue by DexterMagnific** [conan-io/cmake-conan#189]
Hi all,

when using the INSTALL_FOLDER option of conan_cmake_run, the generated compiler options (include paths and link paths) are still the ones of the ~/.conan folder.

My understanding is that if you specify the install folder, package contents are extracted to that dir and the compiler options should point to it.

NOTE: seems that INSTALL_FOLDER works only if you add the "deploy" generator.

Thanks.

**Comment by memsharded** [comment]
Hi @DexterMagnific 

This is not how Conan works. Conan install packages in the local cache, in <userhome>/.conan, always. Packages are installed there because it is the only way that they will not conflict or cause problems when installing different versions of the same package, or even different binaries of the same package with the same version.

The INSTALL_FOLDER of conan_cmake_run refers to the place where the auxiliary generated files (conanbuildinfo.cmake, etc), will be installed. Those are temporary files to consume the things from the local cache, and are typically installed in the user build folder.

Please let me know if this clarifies the issue. Thanks!

**Comment by DexterMagnific** [comment]
Hi @memsharded ,

> Packages are installed there because it is the only way that they will not conflict or cause problems when installing different versions of the same package, or even different binaries of the same package with the same version.

That's exactly for avoiding clashes that I asked this question. Let me expose the problem. With the current approach, the Conan CMake importer inserts a '-isystem /path/to/includes' for every package it imports. We have two issues with this:

- Imported package header files are immediately available without any prefix. That  makes it hard when looking at the code to know from where comes the header file.
- If two packages have the same .h filename, you don't know which one will be used since the two paths are added to the compiler.

To solve this clash problem, I'm looking for a way to have some PREFIX for each one of my imported packages. Installing packages in ~/.conan is not a problem itself, but I'd like a way to make each package have a prefix.

```
#include <my_pk1/my_header.h>
#include <my_pkg2/my_header.h>
```

With the current scheme, I can only do
```
#include <my_header.h>
```

If my app uses the two packages, I can't know which one will be taken since both pkg1 and pkg2 supply the same header file.

Apart from that, I find it better to see in the code the origin of the header file.

THe only solution I see now is to make myself a directory of the name pf the package, which will look ugly because the root dir of the package already has the name of the package:

```
my_pkg/
  my_pkg/my_header.h
  my_pkg/my_lib.so
```

So the import will insert m_pkg in the command line and my includes will be available:

```
#include "my_pkg/...."
```

Thanks

**Comment by memsharded** [comment]
The thing is that the responsibility of providing the correct "namespace" or folder should be the packages, not the consumers. Every package should put the headers in a folder with its name to avoid clashes. It should be the default for packages, and automatic for consumers. It is probably done by many open source packages already, and users should certainly do that with their packages. I am going to file an issue in docs and conan-center-index, to make sure.

**Comment by DexterMagnific** [comment]
Ok. So I will manually add the package name.

**Comment by DexterMagnific** [comment]
I'm sorry but adding a prefix spwans an error when using the package:

```
 WARN: Lib folder doesn't exist, can't collect libraries
```

and there are no more include directives in the compiler command line (probably because of a missing inclide/ folder immediately inside the package. now it has a prefix).

**Comment by DexterMagnific** [comment]
Ok, here is the correct layout:

the package MUST have two folders under root: lib and include

if you want to add a prefix, you must do it UNDER each of lib and include:

```
mypkg/
   include/
       mypkg/
           *.h
   lib/
      mypkg/
           *.so
```

**Comment by memsharded** [comment]
Thanks for following up and telling about the layout.
Actually, the libs don't strictly necessarily need a subfolder, I guess there is something in your ``collect_libs`` or ``package()`` or ``package_info()`` that requires that, but in theory that is not required. Do not hesitate to re-open or post a new issue with more details about your recipe, and we'll try to help. Thanks!
