### ISSUE TITLE
"parse_arguments" macro should have a more specific name

### ISSUE THREAD

**Issue by tjwrona1992** [conan-io/cmake-conan#210]
All of the functions in this module have names that begin with `conan_` and have a low probability of clobbering a user's existing function when the module is loaded, but if a user happens to have a macro named `parse_arguments` and then includes `cmake-conan`, their macro will be overwritten by the `parse_arguments` macro defined in `cmake-conan`.

Although it is unlikely to occur, if `cmake-conan` becomes more popular and the user base grows substantially someone is bound to run into an issue from this at some point. I would suggest simply renaming it to something like `_cmake_conan_parse_arguments` and then the risk of overwriting a user's function would essentially be eliminated.

**Comment by czoido** [comment]
Hi @tjwrona1992,
Thanks for reporting, I agree that it would be better to change the macro's name to avoid collisions so I have opened a PR to fix this.

**Comment by tjwrona1992** [comment]
Awesome thanks!
