### ISSUE TITLE
Consider adding v0.x git tag to track latest backwards compatible version.

### ISSUE THREAD

**Issue by yuri-kilochek** [conan-io/cmake-conan#212]
If/when v1 is released, likewise add v1.x tag.

This would allow zero-effort upgrades for the users while not breaking their code.

**Comment by czoido** [comment]
Hi @yuri-kilochek 
Thanks for the suggestion, for the moment we are using semver, so if we release minor versions they should be backwards compatible, but not for `0.Y.Z` as they are not considered "stable".

**Comment by yuri-kilochek** [comment]
Right. Somehow I forgot about this feature of semver.
