### ISSUE TITLE
[question] Why does cmake_paths generator create separate conan_paths.cmake?

### ISSUE THREAD

**Issue by target-san** [conan-io/cmake-conan#221]
Hello!

This behavior leads to including different CMake scripts based on conanfile.txt, which makes changes in two places instead of one. This also leads to cmake-conan not working with cmake_find_package and cmake_paths properly - conan_paths.cmake are not included into build script.

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment]
Duplicated https://github.com/conan-io/cmake-conan/issues/220
