### ISSUE TITLE
Don't issue "fatal errors" on unknown OS or compiler ID

### ISSUE THREAD

**Issue by simfinite** [conan-io/cmake-conan#227]
Hi all,

as Conan [supports QNX now](https://docs.conan.io/en/latest/integrations/cross_platform/qnx_neutrino.html), I have been working on some preliminary QNX support [over here](https://github.com/simfinite/cmake-conan). 

Before going into details of supporting QNX, I would like to raise the question whether or not  fatal errors should be issued on undetected OS or compiler IDs. The first thing I did in my QNX build experiments was to [turn these fatal errors into warnings](https://github.com/simfinite/cmake-conan/commit/8233e67b214756a3c796a61e6be6289068a61c9e). When passing in all the toolchain details via a profile, it's very prohibiting to have the script error out just because the auto-detection fails. I am sure there are plenty other cases, especially in the embedded world, where this would apply. I found [one already listed](https://github.com/conan-io/cmake-conan/issues/150).

How about disabling the fatal errors when a specific profile is given?

**Comment by czoido** [comment]
Hi @simfinite,
Thanks a lot for the suggestion, I'll open a PR to update the list of the host os's supported as is not reflecting all the ones that are supported by Conan. It also could make sense to change the `ERROR` to a `WARNING` for some cases but should not be needed if we update the supported os's list.

**Comment by simfinite** [comment]
Agreed.

Be aware that QNX is called `QNX` by CMake and `Neutrino` by Conan (see [this commit](https://github.com/simfinite/cmake-conan/commit/7d9917ded74d9ce06a189455327526071bc8d129))
