### ISSUE TITLE
conan_cmake_run enforces that provided CONANFILE is in CMAKE_CURRENT_SOURCE_DIR

### ISSUE THREAD

**Issue by rasjani** [conan-io/cmake-conan#239]
https://github.com/conan-io/cmake-conan/blob/0fb31cd9b99357cb0ecb2b41058daafdef777dc1/conan.cmake#L360

This should imho at least check if the provided CONANFILE argument is already absolute path. Usecase for this (for me) is that because there is no "clean" way to override dependencies (for purpose of verifying that conan packages can be verified before integration), i preprocess the given CONANFILE before passing to `conan_cmake_run`. Preprocess does the required fixes to dependencies and stores new file into build directory (as i dont want to leave the repo into dirty state). But since CMAKE_CURRENT_SOURCE_DIR is prefixed into CONANFILE, conan install will fail ..

**Comment by czoido** [comment]
Hi @rasjani,
Thanks a lot for the feedback. Yes, I think we should take the absolute paths for the CONANFILE, we'll add this for the next release.
