### ISSUE TITLE
Direct integration into cmake

### ISSUE THREAD

**Issue by tonka3000** [conan-io/cmake-conan#24]
Hey,

I like the idea to use cmake to control conan. Are there any chances to integrate that into cmake itself (in the long run), because kitware integrate many 3rdpart libs into cmake?

Greetings
Tonka

**Comment by memsharded** [comment]
Not in our roadmap, you should ask kitware :)
Actually, I think it is a bit early for that, maybe when conan hits 1.0, and specially when this wrapper project (cmake-conan) is much more mature and well-tested, so it gives much better insights in order to face an integration.

**Comment by tonka3000** [comment]
> Not in our roadmap, you should ask kitware :)

I will send a mail to the cmake mailing list, maybe(hopefully) they like the idea.
The conan cmake wrapper is really good and conan is much easier to use with it especially for bigger cmake projects.
So i hope that the wrapper will land in the cmake project directly 😄

**Comment by memsharded** [comment]
Still I feel this wrapper requires more iterations and maturing a bit, it is likely that the interface will still evolve in the coming months, so premature landing in cmake could be counter-productive as it will slow down fixing issues and improving.

In any case, thanks for your support, very glad that you find this wrapper useful, just keep using it and giving feedback, so it can keep improving. It is ok if you still decide to write to the cmake mailing list, this is just my opinion, so up to you :)

Closing the issue by now, as I think it doesn't require an explicit action from our side, but please comment or reopen if this moves forward. Cheers!
