### ISSUE TITLE
Do not try to autodetect settings if profile is specified

### ISSUE THREAD

**Issue by petermbauer** [conan-io/cmake-conan#245]
Although a profile is given to the `conan_cmake_run` function it tries to autodetect settings from cmake. In case of `CMAKE_SYSTEM_NAME` being `Generic` this leads to a fatal error "cmake system Generic is not supported by conan ...". I propose to not perform the autodetection at all in case the profile is given as argument.
IMO this is also according to the documentation (https://github.com/conan-io/cmake-conan/blame/develop/README.md#L144-L146).
see #244

**Comment by czoido** [comment]
Hi,
Proposing this: https://github.com/conan-io/cmake-conan/pull/292 to fix the issue. To be merged in 0.16
