### ISSUE TITLE
conan create fails with can't find conanbuildinfo.cmake

### ISSUE THREAD

**Issue by Arghnews** [conan-io/cmake-conan#249]
I have been trying to use `conan_cmake_run` in my `CMakeLists.txt` files to allow conan to be run in the cmake configure step, such that I can build a project or subproject with (from the source directory) `cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..  && cmake --build .`
This all works nicely.

However, when I now try to package up my project by running, from the source directory, `conan create .`, I get errors originating from `conan.cmake` that it cannot find `conanbuildinfo.cmake`.

I have an example below that I've tried my best to make minimal, to demonstrate the problem.

Directory structure:
- bla
  - CMakeLists.txt
  - conanfile.py
  - bla.cpp

bla/CMakeLists.txt
```cmake
cmake_minimum_required(VERSION 3.14)
project(bla)
set(CMAKE_VERBOSE_MAKEFILE TRUE)
if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
   file(DOWNLOAD "https://github.com/conan-io/cmake-conan/raw/v0.15/conan.cmake" "${CMAKE_BINARY_DIR}/conan.cmake")
endif()
include(${CMAKE_BINARY_DIR}/conan.cmake)
conan_cmake_run(CONANFILE conanfile.py BASIC_SETUP CMAKE_TARGETS BUILD missing)
add_executable(${PROJECT_NAME} bla.cpp)
target_link_libraries(${PROJECT_NAME} PUBLIC CONAN_PKG::range-v3)
```

bla/conanfile.py
```python
from conans import ConanFile, CMake, tools
import shutil

class BlaConan(ConanFile):
    name = "bla"
    version = "0.1"

    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}

    generators = "cmake"
    requires = "range-v3/0.10.0"
    _cmake = None

    def _configure_cmake(self):
        if self._cmake:
            return self._cmake
        self._cmake = CMake(self)
        self._cmake.configure(source_folder = "source_folder", build_folder = "build_folder")
        return self._cmake

    def source(self):
        shutil.copytree("/absolute/path/to/bla", "source_folder")

    def build(self):
        cmake = self._configure_cmake()
        cmake.build()
```

bla/bla.cpp
```cpp
#include <iostream>
#include <range/v3/all.hpp>
int main() { std::cout << "Hello world" << "\n"; }
```

The example code as presented will fail when calling `conan create .` from `bla`. The important bit of the error message from cmake as reported by conan:
```
...
CMake Error at /home/justin/.conan/data/bla/0.1/_/_/build/6e41abfb5a7d95fbe289321565b7c1d2f35255f2/build_folder/conan.cmake:461 (message):
  conanbuildinfo.cmake doesn't exist in
  /home/justin/.conan/data/bla/0.1/_/_/build/6e41abfb5a7d95fbe289321565b7c1d2f35255f2/build_folder
Call Stack (most recent call first):
  /home/justin/.conan/data/bla/0.1/_/_/build/6e41abfb5a7d95fbe289321565b7c1d2f35255f2/build_folder/conan.cmake:502 (conan_load_buildinfo)
  CMakeLists.txt:8 (conan_cmake_run)
...
```
`conan cmake` is complaining that at the path `/home/justin/.conan/data/bla/0.1/_/_/build/6e41abfb5a7d95fbe289321565b7c1d2f35255f2/build_folder` there is no file `conanbuildinfo.cmake`. And it's right, there isn't.

However, that file **is** present, one directory up, at `/home/justin/.conan/data/bla/0.1/_/_/build/6e41abfb5a7d95fbe289321565b7c1d2f35255f2/`?

This very simple example will work if you remove the `build_folder = "build_folder"` in the `conanfile.py`'s cmake.configure call, although this seems more like a coincidence.

My actual use case is more complex and involves nested calls of cmake's `add_subdirectory`, where those subfolders also can't find `conanbuildinfo.cmake` and look in the wrong place - they fail with the same kind of error, not being able to find `conanbuildinfo.cmake`. I have omitted a more complex example (with subdirectories) here as this post is long enough, and I hope if someone can show me a fix for this those may be fixed too.

Ideally a solution would allow me the ability, as I have now, to build my project from the parent or a subproject (each resolving their own conan dependencies) with `cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..  && cmake --build .` or similar, **and** additionally allow `conan create .` from the parent project directory to work.

I would like to ask:
- How can I fix this, what am I doing wrong?
- Is this a poor way to structure a project? If so, what is the alternative? I am presuming what I want is possible but I'm ignorant and perhaps am going about this the wrong way?

Cheers if you've read till here, I realise this is a bit long and appreciate your time.

Ubuntu, x64, Conan 1.26.0, cmake-conan release 0.15, cmake 3.17

**Comment by czoido** [comment]
Hi @Arghnews ,
If you want to use the same `CMakeLists.txt `for both consuming you should differentiate when you are running in the local cache and when in your local folder doing something like this:

```
if(CONAN_EXPORTED) # in conan local cache
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup(TARGETS)
else() # in user space
    if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
    file(DOWNLOAD "https://github.com/conan-io/cmake-conan/raw/v0.15/conan.cmake" "${CMAKE_BINARY_DIR}/conan.cmake")
    endif()
    include(${CMAKE_BINARY_DIR}/conan.cmake)
    conan_cmake_run(CONANFILE conanfile.py BASIC_SETUP CMAKE_TARGETS BUILD missing)
endif()
```

That's probably what's causing your problems. Hope this helps, please check and tell me if it solves your problems.

**Comment by Arghnews** [comment]
Hi @czoido , first of all thanks for the response.

I replaced that section in my `CMakeLists.txt` with your suggestion, however now I get the error:
```
CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

/home/justin/.conan/data/bla/0.1/_/_/build/6e41abfb5a7d95fbe289321565b7c1d2f35255f2/build_folder/conanbuildinfo.cmake

CMake Error at CMakeLists.txt:14 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".
```

where the mentioned lines in the CMakeLists.txt are
```cmake
 11 if(CONAN_EXPORTED) # in conan local cache
 12     message("A")
 13     include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
 14     conan_basic_setup(TARGETS)
 15 else() # in user space
```                                   

The A is printed.

This is running the command `rm -rf ~/.conan/data/bla/ && conan create .` from the source directory.

Again the error being that cmake is looking for `conanbuildinfo.cmake`, expecting it in the directory:
`/home/justin/.conan/data/bla/0.1/_/_/build/6e41abfb5a7d95fbe289321565b7c1d2f35255f2/build_folder/`
However it's actually located in one directory above that, ie. not in `build_folder` but in `build_folder`'s parent (`6e41abfb5a7d95fbe289321565b7c1d2f35255f2`)

Thus it still does not work.

**Comment by bernedom** [comment]
I encountered the same (or at least similar problem) as @Arghnews and opened a pull request to work around the issue by looking for the conan.cmake in multiple locations: 
https://github.com/conan-io/cmake-conan/pull/199

**Comment by Daiqianying** [comment]
@Arghnews 
I'm having the same problem, do you have a solution now?

**Comment by Daiqianying** [comment]
```cmake
if(CONAN_EXPORTED) # in conan local cache
        # standard conan installation, deps will be defined in conanfile.py
        # and not necessary to call conan again, conan is already running
        include(${CMAKE_SOURCE_DIR}/../conanbuildinfo.cmake)
        conan_basic_setup(TARGETS KEEP_RPATHS)
    else() # in user space
        # Make sure to use conanfile.py to define dependencies, to stay consistent
        conan_cmake_run(CONANFILE conanfile.txt.py
                         BASIC_SETUP CMAKE_TARGETS KEEP_RPATHS)
    endif()
```

Here's my solution.
Why does the generated file go to the “${CMAKE_SOURCE_DIR}/../conanbuildinfo.cmake” ?

**Comment by czoido** [comment]
Hi @Daiqianying,
As you are specifying the `source_folder` and `build_folder` in the CMake build helper `configure` method you have to use relative paths to those. The Conan package build folder in the cache is going to be something like: `/Users/carlos/.conan/data/bla/0.1/_/_/build/6c1e424a510a265c345de6c1f610ece3e2b3360f` and there is where the conanbuildinfo.cmake is generated. As this folder will have two subfolders, one the `source_folder` and other the `build_folder` the relative path for that should be `include(${CMAKE_BINARY_DIR}/../conanbuildinfo.cmake)`

**Comment by Daiqianying** [comment]
@czoido   @Arghnews 

Thank you for your responses. Today I found the right solution. You need to create a new CMakeLists.txt like this:

```cmake
cmake_minimum_required(VERSION 3.6.0)
project(HTTPCLIET2_CONANPKG)  # A name you like.

include(${CMAKE_SOURCE_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS KEEP_RPATHS) # Fill in the parameters you need.

add_subdirectory(code) # this is your origin project code
````

this CMakeLists.txt is only for “conan create” use。and you need edit your origin project CMakeLists.txt list this:
```cmake
if(NOT CONAN_EXPORTED) # in user space
        # Make sure to use conanfile.py to define dependencies, to stay consistent
        conan_cmake_run(CONANFILE conanfile.txt
                         BASIC_SETUP CMAKE_TARGETS KEEP_RPATHS)
endif()
```
This will ensure that "conan create" is correct. and your origin project cmake is working properly..

**Comment by Daiqianying** [comment]
@czoido 
poco's conanfile.py clearly points this out.
[poco conanfile.py](https://github.com/pocoproject/conan-poco/blob/master/conanfile.py#L77-L86)

My solution is to make sure that the "conan create" properly and the project itself cmake built properly.

**Comment by czoido** [comment]
Hi @Daiqianying,
If you want to create a wrapper CMake to create your package, normally the solution is the opposite, create a `CMakeLists.txt` with `include(conanbuildinfo.cmake)` so you don't have to modify the `CMakeLists.txt` of your library. This pattern is frequently used in CCI when sources and library are in different locations.
You can check examples for this in CCI repo: [glfw recipe](https://github.com/conan-io/conan-center-index/blob/a53af3004018b06b06f115018dc90333398702e7/recipes/glfw/all/CMakeLists.txt), [aruco recipe](https://github.com/conan-io/conan-center-index/blob/ec062a5e41fc0c1c4b1f020cd8d42346f829c263/recipes/aruco/3.x.x/CMakeLists.txt)

**Comment by czoido** [comment]
As this issue seems solved, I'll close it. Please reopen if you have more questions.
