### ISSUE TITLE
conan_cmake_run(SETTINGS compiler.libcxx=libstdc++11) causes setting to be passed twice

### ISSUE THREAD

**Issue by smessmer** [conan-io/cmake-conan#255]
I use the following lines to invoke conan:

```
conan_cmake_run(
       CONANFILE conanfile.py
       BUILD all
       SETTINGS compiler.libcxx=libstdc++11)
```

However, looking at the build output, I see

```
-- Conan executing: /usr/local/bin/conan install /root/cryfs/conanfile.py -s build_type=RelWithDebInfo -s compiler=gcc -s compiler.version=7 -s compiler.libcxx=libstdc++ -s compiler.libcxx=libstdc++11 -g=cmake --build
```

It seems, it just adds the `compiler.libcxx=libstdc++11` but still emits the `compiler.libcxx=libstdc++` and passes both to `conan install`.

Now it seems that in my case, this does the right thing and sets up the build to use `libstdc++11`, but this seems fishy nevertheless and I'm not sure if I can rely on that behavior.

**Comment by czoido** [comment]
Hi @smessmer,

Thanks a lot for reporting. Yes, it seems like the autodetection of `libcxx` is run regardless of the arguments provided and for this case the `SETTINGS` defined in `conan_cmake_run` should take preference. 
I'll add this fix for the next release.
