### ISSUE TITLE
Support lockfiles in conan_cmake_run()

### ISSUE THREAD

**Issue by rasjani** [conan-io/cmake-conan#271]
Our whole conan usage is based on conan_cmake_run() to avoid both CI and developers to not really care about conan cli usage (eg, everthing can be scripted by setting env variables and/or changes to CMakeLists.txt)

What ever sort of environment its being run, we provide certain parameters to `conan_cmake_run()`. 

In our case, we dont really need lockfiles when building in development env and/or branches but when building for actual release, it would be beneficial to have a lock files.

But it seems that there are no parameters to pass (optional) lockfile to `conan_cmake_run()` or `conan_cmake_install()`

**Comment by czoido** [comment]
Hi @rasjani,
I'm closing this as we have added new functions (`conan_cmake_configure/autodetect/install`) in v0.16 that can replace the flow with `conan_cmake_run` and enable things like using lockfiles or build and host profiles without colliding with the auto-detection. From now on it will be the recommended flow as it is more explicit and flexible.
Please feel free to reopen or open new issues if you have more questions or comments.
