### ISSUE TITLE
Conan profile files from current CMake config

### ISSUE THREAD

**Issue by traceon** [conan-io/cmake-conan#3]
Is there any known way to conveniently generate a Conan profile file from the inside of a CMake config script, to use it directly from that same config a few commands later (by calling `conan` via `execute_process()`?)

BTW: can the Conan system/user config be viewed as a default profile? (So wouldn't it be more consistent to have all the default config, for example, in `.conan/profiles/default` file?)

BTW2: `.conan/conan.conf`, `conanfile.txt`, profile config files and the generated `conaninfo.txt` don't accept all same sections -- is there any rationale behind such limitation?

**Comment by memsharded** [comment]
Hi Denis,

No there is no current way to generate profiles, from CMake or even from conan command line. Those files have to be manually written.  It is a relatively new feature, so creating profiles on the fly hasn't been a thing yet. It tend to be the opposite, we have had some questions regarding how to share profiles between teams, so creating the profiles in a repository and letting the ``--profile`` point to any specific user path was an implemented feature request.

The ``conan.conf`` and profiles are hiearchical (like git configuration). Profiles overwrite (or partially overwrite, if you define it as such) the contents of user ``conan.conf``. Changing that to a ``default`` profile might change behavior and break for a few users.

Conanfile.txt and conaninfo.txt are quite different files. Conanfile.txt is an input file that can be committed to Version Control, serving for many users under different OS and compilers. Conaninfo.txt is the saved snapshot of a the configuration for a certain ``conan install`` invocation. This file shouldn't typically be committed to version control, but it is a good log, to be saved with the binary artifacts. So it contains, for example, the OS, the compiler, etc. That information cannot be stored in conanfile.txt, is not a limitation, it is by definition that it can be the same information.

**Comment by memsharded** [comment]
Hi @traceon,

Besides the questions, I think that there is no specific action required, so I am closing this issue, but please comment or reopen if necessary. A feature request could be that of "conan generating profiles", but as I told you, most of the feedback about the feature actually points in the opposite direction. If you still interested, maybe submit it to the main conan repository to get the feedback of other users.
Thanks!
