### ISSUE TITLE
Support profiles

### ISSUE THREAD

**Issue by memsharded** [conan-io/cmake-conan#30]
Profiles, with things as build_requires are becoming quite powerful, but they are not handled by cmake-conan. Consider some way to add them. 

Possibly:

```bash
CONAN_PROFILE=gcc cmake -G "Unix Makefiles"
```

**Comment by bobeff** [comment]
Is there some progress on this?

**Comment by memsharded** [comment]
Not yet.
Actually i am not pretty sure how will they be applied. If you are using cmake-conan, it means that you are already defining your build, compiler, compiler version, architecture, etc, from cmake. Using a profile for the settings makes no sense at all. At best they will match, but they could also be inconsistent.

They could be useful for optional things as options or build_requires, but not sure how to manage the settings.

**Comment by bobeff** [comment]
I created [pull request](https://github.com/conan-io/cmake-conan/pull/46) with simple solution which we will use internally for now. It overrides automatically determined settings when used.

**Comment by memsharded** [comment]
Merged PR, feature alrady available, many thanks!
