### ISSUE TITLE
Header-only Library how to include

### ISSUE THREAD

**Issue by smac89** [conan-io/cmake-conan#304]
I want to use a header only github project, so I created my `conanfile.py` with this in it:

```py
from conans import ConanFile, tools


class SimpleSignalConan(ConanFile):
    name = "SimpleSignal"
    version = "master"

    def source(self):
        git = tools.Git(folder=self.name)
        git.clone('https://github.com/larspensjo/SimpleSignal.git', branch=self.version)
```

In my `CMakeLists.txt`, I did the following:

```cmake
if(CONAN_EXPORTED) # in conan local cache
    # standard conan installation, deps will be defined in conanfile.py
    # and not necessary to call conan again, conan is already running
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup()
else() # in user space
    include(${CMAKE_BINARY_DIR}/conan.cmake)
    # Make sure to use conanfile.py to define dependencies, to stay consistent
    conan_cmake_run(CONANFILE conanfile.py
                    BASIC_SETUP)
endif()
```

In my `main.cpp`, I tried doing `#include <SimpleSignal.h>`, but it didn't work.

What else do I need in order to be able to `#include <SimpleSignal.h>`?

**Comment by czoido** [comment]
Hi @smac89,

It looks like your recipe is missing some method definitions. You should include the [package](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package) and [package_id](https://docs.conan.io/en/latest/reference/conanfile/methods.html#package-id) methods:
- The `package` method will create the actual package so you can reference the headers later in your project.
- With the `package_id` method you can override the custom package_id generated by conan using `self.info.header_only()` so as it is a header only library, the package will always be the same, irrespective of the settings (OS, compiler or architecture), options and dependencies.

You can check the Conan documentation on [how to package header only libraries](https://docs.conan.io/en/latest/howtos/header_only.html) and also check some examples for header-only projects in conan-center-index: `https://github.com/conan-io/conan-center-index/blob/master/recipes/rapidjson/all/conanfile.py`, [rapidxml](https://github.com/conan-io/conan-center-index/blob/master/recipes/rapidxml/all/conanfile.py), and [nuklear](https://github.com/conan-io/conan-center-index/blob/master/recipes/nuklear/all/conanfile.py).

Please tell me if this helps.

**Comment by smac89** [comment]
@czoido

Thank you for responding to my question. I have updated my `.py` file to the following:

```py
from conans import ConanFile, tools


class SimpleSignalConan(ConanFile):
    name = "SimpleSignal"
    version = 'r0.g0c337f1'
    homepage = 'https://github.com/larspensjo/SimpleSignal'
    no_copy_source = True

    @property
    def _source_subfolder(self):
        return self.name.lower()

    def source(self):
        git = tools.Git(folder=self._source_subfolder)
        git.clone(f'{self.homepage}.git', branch="master")

    def package(self):
        self.copy(f"{self.name}.h", src=self._source_subfolder)

    def package_id(self):
        self.info.header_only()
```

Then at the bottom of my `CMakeLists.txt` file, I have added the following:

```
target_link_libraries(${PROJECT_NAME} ${REQUIRED_LIBS_QUALIFIED} CONAN_PKG::SimpleSignal)
```

But I get the error:
```
CMake Error at CMakeLists.txt:32 (add_executable):
  Target "CLife" links to target "CONAN_PKG::SimpleSignal" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

What am I still missing?

**Comment by smac89** [comment]
@czoido Do you have an example that matches my library? I.e. a single header file imported using conan?

**Comment by czoido** [comment]
Hi @smac89,
I think that you are mixing the consuming and the package creation. Unless you have a CMakelists.txt to create the library I would suggest that you decouple both the creation and the consuming of the library.
A couple of things:
- Please use always lowercase for the library, we will make that mandatory from Conan 2.0.
- Also, change the package definition to use the include dir: `self.copy("SimpleSignal.h", dst="include", src=self._source_subfolder)`
- If you want to use targets (`CONAN_PKG::simplesignal`) please add the `CMAKE_TARGETS` argument to `conan_cmake_run`. 

Doing those changes, a call to `conan create .` in the folder where you have your conanfile.py followed by:

```
cd build 
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
```

With this example _CMakeLists.txt_ should work:

```
cmake_minimum_required(VERSION 2.8)
project(FormatOutput CXX)
set (CMAKE_CXX_STANDARD 11)

if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
   message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
   file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/develop/conan.cmake"
                 "${CMAKE_BINARY_DIR}/conan.cmake" 
                 TLS_VERIFY ON)
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(REQUIRES simplesignal/r0.g0c337f1
                BASIC_SETUP CMAKE_TARGETS
                BUILD missing)

add_executable(main main.cpp)
target_link_libraries(main CONAN_PKG::simplesignal)
```

**Comment by smac89** [comment]
Alright yes that solves the problem. I guess I was assuming that the CMake has the option to both build and install the package and I should still be able to use it in my project.

I guess before I close this, can you explain the purpose of the [last part](https://github.com/conan-io/cmake-conan#creating-packages) of the README, which is what I was trying to follow because it gave me the impression that I could in fact build and use `simplesignal` from my project.

In what situation would that actually work?

**Comment by czoido** [comment]
Hi @smac89,
Yes, you can use the variable CONAN_EXPORTED to check if you are running on Conan's local cache or in user space. That way you can test your project using cmake-conan but also creating the package using Conan commands directly. I thought that for your case it was easier to explain it without making both things as you are just consuming the SimpleSignal package. I have created [a complete example on how to use cmake-conan](https://github.com/czoido/cmake-conan-creator-consumer) for both consuming and creating packages that maybe clears a little the explanation in the docs.

**Comment by czoido** [comment]
I'm closing this issue, please feel free to reopen if you have more questions regarding this topic.
