### ISSUE TITLE
[feature] instead of aborting with an error just add an warning when there's no connection to a remote repository and the package is already in the cache

### ISSUE THREAD

**Issue by SimplyLiz** [conan-io/cmake-conan#314]
When using conan with cmake, conan is called every time during configure/generate.

We're using artifactory as conan repository.
So the first time, all the dependencies are downloaded. When having no internet connection, you can't switch branches or make any changes to cmake. cmake will fail because there's no connection to the remote. Even if everything's cached locally and already available and nothing has changed in terms of version numbers, conan (through cmake) will attempt to check the remote repository, which will fail the entire build.

This is a major blocker for our devs, especially during covid and homeoffice with no stable internet/vpn connection.

Please add at least an option to disable the error and display an warning instead

**Comment by jgsogo** [comment]
Hi, @czoido , can you have a look at this issue? Now that you are also having a look at the `--update` you probably have a better understanding of how it should/could work, if it is related to `cmake-conan` or is something hardcoded into Conan client.

**Comment by czoido** [comment]
Hi @SimplyLiz,

I have been trying to reproduce the issue with no luck, the only two things I can't think of this could happen is:
- Having the `UPDATE` argument in `conan_cmake_run`. Does not seem your case, because in the snippet that argument is not there...
- Having a _conanfile.txt_ with a version range that does not satisfy the version installed in the cache. Could this be the case by any chance?

Could you please detail which conan and cmake-conan versions are you using?

**Comment by SimplyLiz** [comment]
First i want to thank you for looking into this so quickly.

CMake: 3.15.3
Conan: 1.32.1

```
[requires]
openssl/1.1.1i@ETMConanRepo/stable
opcuasdk/1.6.3@ETMConanRepo/stable
iowa/5289_04.01.00.00_16.00.0001@ETMConanRepo/stable
```

at this point i've added those 3 packages to our artifactory. the version or anything doesn't change so far

**Comment by czoido** [comment]
Still no luck :/ ... Could you please copy the output you get? Please, can you detail the cmake-conan wrapper version if you know that (was it 0.15?)

**Comment by SimplyLiz** [comment]
omg, i've just updated to the latest conan.cmake (v0.16)

![image](https://user-images.githubusercontent.com/7029836/109154994-5a00a900-776f-11eb-9b62-c8b24f4f7645.png)

and it seems to work! sry i should have checked for an update before creating an issue. 
Thank you so much for looking into that!

**Comment by czoido** [comment]
Great! Please feel free to reopen or add more issues if you have further problems

**Comment by gsantner** [comment]
Hello @czoido (or guess @memsharded ?), may I ask a question:

Is there any way to force conan-cmake to work offline? There was seemingly a way in Conan1-cmake, but not in Conan2 (develop2)?
As It's top level include now and always runs conan install, I can't skip running conan install currently?

I have all required packages built and in local cache that are needed by application.
Thank you!
