### ISSUE TITLE
Why is there no way to link libraries using the conan_target_link_libraries() notation since cmake-conan v0.16?

### ISSUE THREAD

**Issue by saracen24** [conan-io/cmake-conan#317]
The Conan documentation [`conan_target_link_libraries()`](https://docs.conan.io/en/latest/reference/generators/cmake.html#conan-target-link-libraries) for the `cmake` generator specifies the ability to link libraries as `CONAN_PKG::<PKG-NAME>`. Can I only link with `find_package()` now?

**Comment by czoido** [comment]
Hi @saracen24,
You can still use the cmake generator if you wish. Please check this example in tests:

https://github.com/conan-io/cmake-conan/blob/e17c8d12b5e09d2dcb9d8ec00cc4b37a6bbe7784/tests.py#L157-L171

**Comment by saracen24** [comment]
Thanks @czoido!
In the future using separate calls to `conan_cmake_configure`, `conan_cmake_autodetect` and `conan_cmake_install` will be deprecated. `conan_basic_setup` will be supported as before?
