### ISSUE TITLE
conan_cmake_detect_unix_libcxx fails with older cmake versions

### ISSUE THREAD

**Issue by jsinge** [conan-io/cmake-conan#324]
I ran cmake-conan0.16.1 on Ubuntu 18.04 with a custom cmake installation version 3.7.2 and experienced this error:

> CMake Error at scripts/conan.cmake:345 (separate_arguments):
>   separate_arguments given unknown argument NATIVE_COMMAND
> Call Stack (most recent call first):
>   scripts/conan.cmake:142 (conan_cmake_detect_unix_libcxx)
>   scripts/conan.cmake:433 (_conan_detect_compiler)
>   CMakeLists.txt:88 (conan_cmake_autodetect)

The cmake-conan documentation states compatibility:

> cmake_minimum_required(VERSION 3.5)

But in fact NATIVE_COMMAND is only available from CMAKE 3.9 on. (see https://cmake.org/cmake/help/latest/command/separate_arguments.html )

I fixed this in my project by upgrading CMake.
For cmake-conan I want to suggest to update the cmake_minimum_required version to 3.9

**Comment by czoido** [comment]
Hi @jsinge,
Thanks a lot for reporting, you are right, we should raise the minimum CMake version. We'll add these changes for the next release.
