### ISSUE TITLE
[Question] How to use conanfile.txt with new API ?

### ISSUE THREAD

**Issue by redradist** [conan-io/cmake-conan#331]
I've read updated README.md:
```
conan_cmake_run() high level wrapper

This function is not the recommended way of using cmake-conan any more and will be deprecated in the near future ...
```
But only this function is support `conanfile.txt` !!

@czoido
How to use `conanfile.txt` with new API ?

**Comment by redradist** [comment]
Seems like I've figured out how to use `conanfile.txt` that is already exists:
```
conan_cmake_autodetect(settings)
conan_cmake_install(PATH_OR_REFERENCE ${CMAKE_SOURCE_DIR}
                    BUILD missing
                    REMOTE conan-center
                    SETTINGS ${settings})
```
Just do not use `conan_cmake_configure` function

**Comment by czoido** [comment]
Hi @redradist,
Thanks for the question. Yes, that's exactly how to do that, `conan_cmake_configure` is the function to create a conanfile.txt on the fly and just not calling that is enought. I'll add an extra note in the README to clarify this.

**Comment by IceflowRE** [comment]
I tried to port from `conan_cmake_run` to the new recommended strategy, but unfortunately the headers are not longer found.
Did i missed something?

**Comment by czoido** [comment]
Hi @IceflowRE,
Could you please share some more details on how you changed things? 
Which calls are you making and with what arguments?

**Comment by IceflowRE** [comment]
> 
> 
> Hi @IceflowRE,
> Could you please share some more details on how you changed things?
> Which calls are you making and with what arguments?

Found it:
I had to add after `conan_cmake_install`
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```
