### ISSUE TITLE
Wrong example in readme

### ISSUE THREAD

**Issue by vdsbenoit** [conan-io/cmake-conan#338]
### Error in the readme
In the release 0.16 and current develop readme, the example in the [conan_cmake_install](https://github.com/conan-io/cmake-conan#conan_cmake_install) description is still the example of the previous `conan_cmake_run` command.

### cmake generator
I take the opportunity of this ticket to provide some feedback on the recent update for the documentation. I have to admit I am confused with the examples of the new API (with `conan_cmake_install`) because the `cmake_find_package` generator is used. I think it is not consistant with other examples that use the casual `cmake` generator. 

Due to this, when I tried to update my code to the new API, it took me a while to understand that the `conan_cmake_install` macro does not accept any `BASIC_SETUP` nor `CMAKE_TARGETS` arguments anymore and that we should call `conan_basic_setup(TARGETS)` instead. I found it out when I read this [issue](https://github.com/conan-io/cmake-conan/issues/317). I think it would be worth it to document this change.

That said, thank you for the great work you have provided here, it is much appreciated 🙏

**Comment by czoido** [comment]
Hi @vdsbenoit,
Thanks for reporting this issue and your feedback. Also, thanks a lot for your kind word.
We'll fix the `conan_cmake_install` asap and also make it clearer the switch to `find_package` generator in the documentation. The reason for the update to the `find_package` generator is that it's less intrusive and more aligned with the direction we want Conan to take for 2.0. I'll try to clarify the change in the docs.

**Comment by vdsbenoit** [comment]
Hi @czoido,

Thank you for updating the documentation. I had a look at your PR and it looks good to me.

May I also suggest to split the documentation in two different pages ? One for the 3 new macros (`conan_cmake_install` etc) and another for the previous macro (`conan_cmake_run`). While reading the current readme, I felt like jumping from an implementation to another which lead to a lot of confusion. Another colleague just shared the same feeling with me today so I thought it was worth sharing it with you.
