### ISSUE TITLE
How to get the env_info.PATH by `conan_cmake_run`?

### ISSUE THREAD

**Issue by zhen8838** [conan-io/cmake-conan#344]
I want to use flatc during the building, and the path has been appended when the configure:
```sh
flatbuffers/2.0.0: Appending PATH environment variable: /root/.conan/data/flatbuffers/2.0.0/_/_/package/3d5f99e0f58b3b3313835fd7e59f60581f0f9dde/bin
but I use cmake build will raise error as:
```
command not found: flatc
```
I use `conan build` it can find the `flatc`
```
How to auto get the flatc path when using `conan_cmake_run`?

**Comment by czoido** [comment]
Hi @zhen8838,
If you want to have `flatc` in the path you may use the `VirtualRunEnv` generator. Add the generator and then you can run `source conanrun.sh`.
Hope this helps.

**Comment by zhen8838** [comment]
ok thanks.
