### ISSUE TITLE
conan_cmake_run fails when conan is installed inside docker and then used

### ISSUE THREAD

**Issue by piratlasaikiran** [conan-io/cmake-conan#346]
I installed conan inside docker with this 

`RUN sudo python3 -m pip install conan
`
And after starting docker container I have these lines in my CMakeFile.txt

```
conan_cmake_run(
    REQUIRES
    ${CONAN_PACKAGES})
```
While running the cmakefile I'm getting this error

```
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Debug;-s;compiler=gcc;-s;compiler.version=8;-s;compiler.libcxx=libstdc++11
-- Conan: checking conan executable
-- Conan: Found program /usr/bin/conan
-- Conan: Version found 
-- Conan executing: /usr/bin/conan install . -s build_type=Debug -s compiler=gcc -s compiler.version=8 -s compiler.libcxx=libstdc++11 -g=cmake
CMake Error at cmake/conan.cmake:402 (message):
  Conan install failed='No such file or directory'
Call Stack (most recent call first):
  cmake/conan.cmake:497 (conan_cmake_install)
  CMakeLists.txt:17 (conan_cmake_run)


-- Configuring incomplete, errors occurred!

```
After debugging, I realised that conan is looking for a local installation instead of global. (I may be wrong here). 
What I should do here?

**Comment by czoido** [comment]
Hi @piratlasaikiran,
Please check the argument [CONAN_COMMAND](https://github.com/conan-io/cmake-conan#conan_command) that should help to find conan.
Please tell me if this helps.

**Comment by piratlasaikiran** [comment]
@czoido This worked.
Thanks.!!

**Comment by czoido** [comment]
Glad to hear!, I'm closing this issue then
