### ISSUE TITLE
Question: Is the compiler.libcxx setting required also for C projects (using gcc)?

### ISSUE THREAD

**Issue by senr80** [conan-io/cmake-conan#348]
Hi,

I'm using cmake-conan in a CMake C project. I call `conan_cmake_autodetect()` and pass on these settings to the call of `conan_cmake_install()`. Generally, this works as expected, e.g. for C++ projects or when building with the Microsoft Compiler.

If I want to use gcc to build the C project, Conan complains for missing the `compiler.libcxx` settings attribute. Looking into `cmake-conan.cmake` I see that the detection includes this only if `CXX` is set in the global `ENABLED_LANGUAGES` property. This fits with my understanding of the meaning of this setting.

As a workaround I can add `CXX` to the languages in the `project()` call in the project's CMake script and this attribute is included in the detected settings. But I'm wondering if I missed something about how to do this in the right way for a C project. Maybe the language to use needs to get passed to Conan somehow or some special value is required in `compiler.libcxx`? I wasn't able to find any hint about that.

thanks in advance for any help!

**Comment by czoido** [comment]
Hi @senr80,
I suspect that your fail is related to using a `C` library that does not delete settings that don't make sense for C libraries in the conanfile, could that be the problem? Typically for `C` libraries you have to delete things like `self.settings.compiler.libcxx` or `self.settings.compiler.cppstd` so it will be ok if the consumer does not define them like in this case. You can check that in some `C` recipes like this one: https://github.com/conan-io/conan-center-index/blob/0ab573f98365189d16afa3ecf4478482fb4f7514/recipes/tiny-bignum-c/all/conanfile.py#L36-L40 in conan-center-index. 
Please tell me if this helps.

**Comment by senr80** [comment]
@czoido Indeed, it works now - thanks a lot!
Like in the recipe you linked to I delete the `self.settings.compiler.libcxx` and `self.settings.compiler.cppstd` (actually, deleting `libcxx` only already did help) in my recipe's `configure()` method now and the install step runs fine.

I'm wondering: Is this something I could have found in the Conan docs somewhere? Or is this something one just needs to know?

**Comment by czoido** [comment]
Hi @senr80, 
I'm glad it helped! There are a couple of mentions to this in the docs [here](https://docs.conan.io/en/latest/faq/troubleshooting.html#error-setting-value-not-defined) and [here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#configure-config-options) but maybe the best source of information is having a look at how recipes are made in conan-center-index: https://github.com/conan-io/conan-center-index/tree/master/recipes.
I'm closing this as this seems solved, but please feel free to reopen or open new issues if you have further questions.
