### ISSUE TITLE
How to enable revisions

### ISSUE THREAD

**Issue by Dudly01** [conan-io/cmake-conan#352]
I am trying to install the package [imgui-sfml](https://github.com/bincrafters/community/tree/main/recipes/imgui-sfml) from the bincrafters artifactory remote. However, during CMake configuration I  get the following error message:

```
[cmake] ERROR: The remote at 'https://bincrafters.jfrog.io/artifactory/api/conan/public-conan' only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1 or set 'general.revisions_enabled = 1' at the 'conan.conf'. [Remote: bincrafters]
```
The [conan documentation](https://docs.conan.io/en/latest/versioning/revisions.html#how-to-activate-the-revisions) gave me a better idea on what needs to be done. However, I was unable to find the way of setting it from CMake.

Setting it as a [command line environment variable](https://docs.conan.io/en/latest/versioning/revisions.html#how-to-activate-the-revisions) did not help, so that must not be what I am looking for.

**Comment by aberegovoy** [comment]
Hello. I could share what I came to. Basically, I copied some function from the cmake-conan:

```cmake
# The cmake-conan helpers

include(cmake/conan.cmake)

function(conan_config_set)                                                      
    # Set a config value.                                                       
    # Arguments NAME and VALUE are required                                     
    # Example usage:                                                            
    #    conan_config_set(NAME general.revision_enabled                         
    #                     VALUE 1)                                              
    #                                                                           
    # See: https://docs.conan.io/en/latest/reference/commands/consumer/config.html
                                                                                
    set(oneValueArgs NAME VALUE)                                                
    cmake_parse_arguments(CONAN "" "${oneValueArgs}" "" ${ARGN})                
                                                                                
    if(DEFINED CONAN_COMMAND)                                                   
        set(CONAN_CMD ${CONAN_COMMAND})                                         
    else()                                                                      
        conan_check(REQUIRED)                                                   
    endif()                                                                     
                                                                                
    message(STATUS "Conan: Setting ${CONAN_NAME} to ${CONAN_VALUE}")            
                                                                                
    execute_process(COMMAND ${CONAN_CMD} config set ${CONAN_NAME}=${CONAN_VALUE}
                    RESULT_VARIABLE return_code)                                
    if(NOT "${return_code}" STREQUAL "0")                                       
        message(FATAL_ERROR "Conan config set failed='${return_code}'")         
    endif()                                                                     
endfunction()

# Enable revisions support on the client.                                       
conan_config_set(NAME general.revisions_enabled VALUE 1)
```

**Comment by czoido** [comment]
Hi @Dudly01, @aberegovoy 
A possible solution is create your own wrapper for `conan config set` command. Also, there's already a wrapper for `conan config install` in cmake-conan so you can have all the configuration in a file or a remote and install it from there. This is very convenient to share the full conan configuration between different clients. Please check [cmake-conan](https://github.com/conan-io/cmake-conan#conan_config_install) docs and [conan docs about this](https://docs.conan.io/en/1.36/reference/commands/consumer/config.html#conan-config-install).

**Comment by Dudly01** [comment]
Thank you for your help @aberegovoy, you solved my issue.
Thank you @czoido , once I dive a bit deeper than making example codes work, I will try the approach you suggested.
