### ISSUE TITLE
[question] Using boost components with CMake

### ISSUE THREAD

**Issue by maximiliank** [conan-io/cmake-conan#355]
I am trying to use boost components from conan with CMake. Following the documentation my `CMakeLists.txt` looks like:

```
cmake_minimum_required(VERSION 3.20)
project(boost_conan_components)

set(CMAKE_CXX_STANDARD 20)

macro(run_conan)
    list(APPEND CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
    list(APPEND CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})

    if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
        message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
        file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v0.16.1/conan.cmake"
                "${CMAKE_BINARY_DIR}/conan.cmake"
                EXPECTED_HASH SHA256=396e16d0f5eabdc6a14afddbcfff62a54a7ee75c6da23f32f7a31bc85db23484
                TLS_VERIFY ON)
    endif()

    include(${CMAKE_BINARY_DIR}/conan.cmake)

    conan_cmake_configure(
            REQUIRES
            boost/1.74.0
            GENERATORS cmake_find_package)

    conan_cmake_autodetect(settings)

    conan_cmake_install(PATH_OR_REFERENCE .
            BUILD missing
            REMOTE conan-center
            SETTINGS ${settings})
endmacro()

run_conan()

find_package(Boost 1.74 COMPONENTS system REQUIRED)

add_executable(boost_conan_components main.cpp)
target_link_libraries(boost_conan_components Boost::system)
```

It is working and finding the `system` component
```
-- Conan: Using autogenerated FindBoost.cmake
-- Conan: Component 'system' found in package 'Boost'
```
but it also finds all the other boost libraries
```
-- Library boost_contract found /home/<user>/.conan/data/boost/1.74.0/_/_/package/8468b057bf5b2cf5c1e9194777c025a4812bc62f/lib/libboost_contract.a
-- Found: /home/<user>/.conan/data/boost/1.74.0/_/_/package/8468b057bf5b2cf5c1e9194777c025a4812bc62f/lib/libboost_contract.a
-- Library boost_coroutine found /home/<user>/.conan/data/boost/1.74.0/_/_/package/8468b057bf5b2cf5c1e9194777c025a4812bc62f/lib/libboost_coroutine.a
-- Found: /home/<user>/.conan/data/boost/1.74.0/_/_/package/8468b057bf5b2cf5c1e9194777c025a4812bc62f/lib/libboost_coroutine.a
...
```

Is this the correct way to use boost components from CMake and can the search for the other libraries be disabled?
I am using conan version 1.39.0.

**Comment by czoido** [comment]
Hi @maximiliank,
Thanks for the question and sorry for the late response.
Yes, that is the correct way to use components. Adding the `COMPONENTS system` will check if that target is available and error if it's not. The meaning of that is not that it will just "import" that component as targets for all components will be declared.
The library detection inside the generated `FindBoost.cmake` will always be run no matter if you use components or the global target.

**Comment by Bjoe** [comment]
I only enable in my projects the boost components that I need during the `conan_cmake_configure()` command. See my example https://github.com/Bjoe/cmake-conan/blob/crosscompile-boost/CMakeLists.txt#L29-L59
This speed up also the build :-)

Maybe also a solution for you @maximiliank ?

**Comment by maximiliank** [comment]
Thank you, that's the solution I was looking for!
