### ISSUE TITLE
[Question] How to set output dirs with cmake_find_package generator

### ISSUE THREAD

**Issue by ssafet-qb** [conan-io/cmake-conan#358]
```
conan_cmake_run() high level wrapper

This function is not the recommended way of using cmake-conan any more and will be deprecated in the near future ...
```

Right now I'm trying to switch to conan_cmake_autodetect(), conan_cmake_install() but conan_cmake_run() was setting:
- set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
- set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
- set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

How can I set these output dirs from conan with conanfile.py and generator:cmake_find_package/cmake_find_package_multi?

**Comment by czoido** [comment]
Hi @ssafet-qb,
This will not be set as it was with the cmake generator, but you can set that in your CMakeLists.txt
Are you running into problems because of this? Please tell us if you need help moving from one model to other.

**Comment by ssafet-qb** [comment]
With conan.cmake from the main branch we don't have this issue.
