### ISSUE TITLE
Full rebuild after cmake

### ISSUE THREAD

**Issue by kolis** [conan-io/cmake-conan#36]
Every time I run `cmake`, the whole project rebuilds, even if nothing has changed. Our full build takes quite long time and want to avoid redundant building whenever possible.

I have traced this problem to a sequence of whitespace being added to the compiler command line, which cause every source file to be recompiled!

I think the root cause of this is in the `conanbuildinfo.cmake`, in the `conan_define_targets` macro. It contains
```
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CONAN_CMD_CXX_FLAGS}")
```
And `CONAN_CXX_FLAGS`  get an additional whitespace every time it is evaluated.
```
set(CONAN_CXX_FLAGS " ${CONAN_CXX_FLAGS}")
```

Same thing with `CMAKE_C_FLAGS`, `CMAKE_SHARED_LINKER_FLAGS`

**Comment by memsharded** [comment]
I am trying to figure out what could be happening but still no idea. I am working with a normal project (not using cmake-conan), with a ``conanbuildinfo.cmake``, and re-launching project generation and project build, and it doesn't get fully rebuild.

These cmake quirks are quite annoying. What cmake version are you running? I have tried with 3.7. Do you have a fully reproducible behavior of this issue? Thanks!

**Comment by kolis** [comment]
It does not rebuild for a small standalone example!

I have found the problem, it is a combination of the conan flag setting and our internal flag modifications. We have a macro to remove flags depending on cmake settings.
```cmake
MACRO(AGX_REMOVE_CXX_FLAG flag)
  IF (CMAKE_CXX_FLAGS)
    STRING(REGEX REPLACE " *${flag}" "" CMAKE_CXX_FLAGS_TMP ${CMAKE_CXX_FLAGS})
    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS_TMP}" CACHE STRING "" FORCE)
  ENDIF()
ENDMACRO()
```
Even if this does not change the flag string it modifies some internal cmake state. I have printed `CMAKE_CXX_FLAGS` before and after calling this macro and it has the same value. But still, this in combination with conan cmake flags will cause whitespace to appear. If I completely remove calls to either conan or `AGX_REMOVE_CXX_FLAG` then the problem disappear.

I have modifed our macro to only re-set the flags if the regex did some modification.

```cmake
MACRO(AGX_REMOVE_CXX_FLAG flag)
  IF (CMAKE_CXX_FLAGS)
    STRING(REGEX REPLACE " *${flag}" "" CMAKE_CXX_FLAGS_TMP ${CMAKE_CXX_FLAGS})
    IF (NOT (CMAKE_CXX_FLAGS_TMP STREQUAL CMAKE_CXX_FLAGS))
      SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS_TMP}" CACHE STRING "" FORCE)
    ENDIF()
  ENDIF()
ENDMACRO()
```
 
Now I don't see this problem any more.

**Comment by memsharded** [comment]
Great! Very glad you were able to fix it. 
Definitely, the CMake quirks can be a nightmare sometimes. Thanks very much for reporting the solution.

**Comment by effolkronium** [comment]
maybe it's better to fix it on cmake side so no one need to change their scripts ?...
