### ISSUE TITLE
SSLError when resolving anything from Conan Center

### ISSUE THREAD

**Issue by iurii-provizio** [conan-io/cmake-conan#365]
Dear cmake-conan team,

Since at least yesterday I'm unable to resolve anything from Conan Center using cmake-conan v0.16.1 with the following error:

```
[cmake] gtest/1.11.0: Not found in local cache, looking in remotes...
[cmake] gtest/1.11.0: Trying with 'conancenter'...
[cmake] ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

(WSL2 version of Ubuntu 20.04, cmake version 3.16.3.)
Example:

```
conan_cmake_run(REQUIRES 
                    gtest/1.11.0
                BASIC_SETUP
                CMAKE_TARGETS
                BUILD missing
)
```

Tried multiple wi-fi networks, checked https://conan.io/center/ is available alright (it is), cleaned-up the CMake build directory - nothing helps. Is it something down on the Conan Center side and should be reported to them, or something changed in their API, which is not supported by cmake-conan v0.16.1?

**Comment by ledocc** [comment]
Same issue for me, I just updated conan to 1.40.3 to fix it.
HTH
David

Le ven. 1 oct. 2021 à 17:28, Iurii Ivanov ***@***.***> a
écrit :

**Comment by memsharded** [comment]
Yes, this is not a cmake-conan issue, but a Conan one. Please track https://github.com/conan-io/conan/issues/9695 for information. In short

- Upgrade to 1.40.3
- Or ``conan config install https://github.com/conan-io/conanclientcert.git`` for previous versions
- Or upgrade your cacert.pem if you use your own configuration in ``conan config install``
