### ISSUE TITLE
Setup repo to use cmake fetch content module

### ISSUE THREAD

**Issue by WilliamBehrens** [conan-io/cmake-conan#368]
I was wonder if there is a reason not to use cmakes' [FetchContent](https://cmake.org/cmake/help/v3.11/module/FetchContent.html) module. It seems like it would reduce the amount of boilerplate needed to set up cmake-conan?

**Comment by czoido** [comment]
Hi @WilliamBehrens,
Could you give a bit more information on how using FetchContent would reduce the amount of boilerplate code to setup cmake-conan?
Thanks a lot.

**Comment by WilliamBehrens** [comment]
### current boilerplate
```cmake
list(APPEND CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
list(APPEND CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})

if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
  message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
  file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v0.16.1/conan.cmake"
                "${CMAKE_BINARY_DIR}/conan.cmake"
                EXPECTED_HASH SHA256=396e16d0f5eabdc6a14afddbcfff62a54a7ee75c6da23f32f7a31bc85db23484
                TLS_VERIFY ON)
endif()
```

### boilerplate with fetch content
```cmake
include(FetchContent) 
FetchContent_Declare(cmake-conan GIT_REPOSITORY https://github.com/conan-io/cmake-conan.git) 
FetchContent_MakeAvailable(cmake-conan)
```

**Comment by czoido** [comment]
Hi, thanks for the suggestion, but I think that in the sake of simplicity we should keep it like it is, also doing so you don't have to clone the entire repo but only the cmake file you want to use.
