### ISSUE TITLE
When is next release scheduled?

### ISSUE THREAD

**Issue by Zvicii** [conan-io/cmake-conan#369]
I wish to try out the latest visual studio 2022 using conan and cmake, I see in branch develop its already supported(#350), so Im wondering when is next release. Or am I supporsed to use banch develop?

**Comment by czoido** [comment]
Hi @Zvicii,
We will release 0.17 before the end of this month. 
Thanks for your patience and sorry for the inconvenience

**Comment by Zvicii** [comment]
Thank you for your quick reply, its very helpful!

**Comment by czoido** [comment]
Hi @Zvicii,
We have just released version 0.17. with those changes included: https://github.com/conan-io/cmake-conan/releases/tag/0.17.0
