### ISSUE TITLE
Tag for version 0.17.0 is missing 'v'

### ISSUE THREAD

**Issue by Novakov** [conan-io/cmake-conan#371]
All previous releases in this repository have tags `v<version>` (with leading `v`), however latest release has tag name following different pattern - `0.17.0` (no leading `v`). 

Is this intended or by mistake?

**Comment by czoido** [comment]
Hi @Novakov,
Yes, this was intended to make create the tags with the same format as we do in the Conan client repo.
Thanks a lot.

**Comment by Novakov** [comment]
Ok, thanks for quick reply!
