### ISSUE TITLE
How to use version 0.17.0?

### ISSUE THREAD

**Issue by wouterbeek** [conan-io/cmake-conan#382]
The latest version of this tool is 0.17.0, but the documentation shows how to use 0.1.6.1:

```cmake
file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v0.16.1/conan.cmake"
```

Changing "0.16.1" into "0.17.0" results in a non-existing resource.  It is also not immediately clear how the secure hash should be generated for the new version.

**Comment by czoido** [comment]
Hi,
We removed the v from the tag to make it consistent with the Conan client tags, sorry it affected you. Just use: https://raw.githubusercontent.com/conan-io/cmake-conan/0.17.0/conan.cmake

**Comment by wouterbeek** [comment]
@czoido Thanks for the quick reply!

The following CMake snippet most closely corresponds to the one currently in the README file:

```cmake
if(NOT EXISTS ${CMAKE_BINARY_DIR}/conan.cmake)
  message(STATUS "Downloading conan.cmake 0.17.0.")
  file(
    DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/0.17.0/conan.cmake"
    ${CMAKE_BINARY_DIR}/conan.cmake
    EXPECTED_HASH SHA256=3bef79da16c2e031dc429e1dac87a08b9226418b300ce004cc125a82687baeef
    TLS_VERIFY ON)
  endif()
endif()
include(${CMAKE_CURRENT_BINARY_DIR}/conan.cmake)
```

^ There are actually some issues with how this CMake code snippet handles failing downloads; I'm opening #383 for that, since that's a different issue.

The SHA hash was checked manually by me by running the following command:

```sh
wget https://raw.githubusercontent.com/conan-io/cmake-conan/0.17.0/conan.cmake
sha256sum conan.cmake 
3bef79da16c2e031dc429e1dac87a08b9226418b300ce004cc125a82687baeef  conan.cmake
```
