### ISSUE TITLE
Conan package is not downloaded from remote (artifactory)

### ISSUE THREAD

**Issue by ano33** [conan-io/cmake-conan#388]
Hi, I am trying to download a conan package from my company's artifactory server. This is my code:

```
list(APPEND CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
list(APPEND CMAKE_PREFIX_PATH ${CMAKE_BINARY_DIR})
if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
  message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
  file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/v0.16.1/conan.cmake"
                "${CMAKE_BINARY_DIR}/conan.cmake"
                EXPECTED_HASH SHA256=396e16d0f5eabdc6a14afddbcfff62a54a7ee75c6da23f32f7a31bc85db23484
                TLS_VERIFY ON)
endif()
include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_add_remote(NAME artifactory
                       INDEX 1
                       URL https://artifactory.<company>/artifactory/api/conan/<project>
                       VERIFY_SSL True)

conan_cmake_configure(OPTIONS MYPACKAGE:include_gtest=FALSE
                                        SETTINGS build_type=${CMAKE_BUILD_TYPE} os=Linux MYPACKAGE:os.distro=${OS} arch=x86_64 compiler=gcc)

conan_cmake_install(PATH_OR_REFERENCE .
                         INSTALL_FOLDER ${MYPACKAGE_LIB}
                         BUILD MYPACKAGE
                         REMOTE artifactory
                         SETTINGS build_type=${CMAKE_BUILD_TYPE} os=Linux MYPACKAGE:os.distro=${OS} arch=x86_64 compiler=gcc
                         OPTIONS MYPACKAGE:include_gtest=FALSE)
```

There are no errors and everything seems to work, but when I take a look inside the directory MYPACKAGE_LIB (the package MYPACKAGE should be installed here from the remote), there is no package, only some conan files. I have some custom settings but I don't think that they are the problem. Is it possible to use this wrapper to download conan packages from artifactory? Or is it only possible for the conan-center?

**Comment by czoido** [comment]
Hi @ano33,
Yes, that's expected, the actual packages are stored in the Conan local cache (tipically under `~/.conan/data`) and the files that appear in your install folder are just referencing to those files stored there. 
There are mechanisms in Conan to take files from the local cache to the developer folders like the [imports method](https://docs.conan.io/en/latest/reference/conanfile/methods.html#imports) and also for the case of dynamic libraries Conan can generate a script that generates the needed environment variables to find those (check the [VirtualRunEnv](https://docs.conan.io/en/latest/reference/conanfile/tools/env/virtualrunenv.html) docs).
Hope this helps

**Comment by ano33** [comment]
Hello @czoido 
thank you very much, you really helped me there!
