### ISSUE TITLE
Package dependency collision

### ISSUE THREAD

**Issue by Timen** [conan-io/cmake-conan#391]
I'm trying to add some conan packages to my cmake project namely opencv & boost. When I do so using the following two cmake function calls:
```
conan_cmake_run(REQUIRES opencv/4.3.0@channel/user
        BASIC_SETUP CMAKE_TARGETS
        BUILD missing
        PROFILE_AUTO ALL)
conan_cmake_run(REQUIRES boost/1.73.0@channel/user
        BASIC_SETUP CMAKE_TARGETS
        BUILD missing
        PROFILE_AUTO ALL)
```

I get an error in the second call that looks like this:
```
 add_library cannot create imported target "CONAN_LIB::zlib_z" because
  another target with the same name already exists.
```
It seems the problem is that both opencv & boost have a zlib dependency which is being added a second time in the setup of the boost package. It seems quite a common occurrence that multiple packages have a dependency for the same package. What is the recommend way to deal with this in cmake-conan?

**Comment by czoido** [comment]
Hi @Timen,

You should make a single call to `conan_cmake_run` using the two dependencies as arguments: `REQUIRES opencv/4.3.0@channel/user boost/1.73.0@channel/user` also, please check the new recommended way of using cmake-conan with separate calls to: `conan_cmake_configure`, `conan_cmake_autodetect` and `conan_cmake_install`

Hope this helps!

**Comment by Timen** [comment]
Thanks for the quick answer @czoido just one question, let's say one of the two packages is only used in certain configuration setups, that means I just need to setup two different calls to `conan_cmake_configure(REQUIRES` correct? I can't append to the REQUIRES list after the fact?

**Comment by czoido** [comment]
If you have conditional requirements, you may want to switch to use a conanfile.py to specify your requirements and add all the logic there, there's a section in Conan docs where it's explained how to do that: https://docs.conan.io/en/latest/mastering/conditional.html#conditional-settings-options-and-requirements
Would that fit your needs?

**Comment by Timen** [comment]
That would probably work as-well but seems less convenient I'll just stick to either using:
```
conan_cmake_configure(REQUIRES opencv/4.3.0@channel/user
                                                             boost/1.73.0@channel/user 
                                            GENERATORS cmake_find_package_multi)
```
or
```
conan_cmake_configure(REQUIRES opencv/4.3.0@channel/user
                                            GENERATORS cmake_find_package_multi)
```

Depending on the build configuration.

**Comment by Timen** [comment]
thanks for the info! I think this is probably something to add to the Readme, I may open a pr for that later on once I have some more familiarity.
