### ISSUE TITLE
using cmake_multi with conan cmake

### ISSUE THREAD

**Issue by Ju1He1** [conan-io/cmake-conan#393]
Hey guys,
I'm having trouble the get the cmake_multi generator to work for me.

We are using almost the recommended way for to generate and install conan packages. This means

```

conan_cmake_configure(REQUIRES tinyxml/2.6.2
GENERATORS cmake_find_package qmake)

#for multiconfig generators we have to build both debug and release
    message("Running debug build")
    #Debug
    conan_cmake_autodetect(settings BUILD_TYPE Debug)
    conan_cmake_install(
      PATH_OR_REFERENCE
      .
      BUILD
      missing
      GENERATOR
      cmake_multi
      SETTINGS
      ${settings}
      SETTINGS_HOST
      build_type=Debug
    )

    #Release
    message("Running release build")
    conan_cmake_autodetect(settings BUILD_TYPE Release)
    cmake_print_variables(settings)

    conan_cmake_install(
      PATH_OR_REFERENCE
      .
      BUILD
      missing
      GENERATOR
      cmake_multi
      SETTINGS
      ${settings}
      SETTINGS_HOST
      build_type=Release
    )
find_package(TinyXML REQUIRED)
```

According to https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_multi_generator.html
for multi config generators we have to call conan install for the Debug and Release build, that's why we added 2 calls to conan cmake install

However this results in a linker error
`tinyxml.lib(tinyxml.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in foo.obj [C:\jenkins\workspace\core_codecs.vcxproj]`
=> there seems to be a mismatch between the build types in the 3rd parties and the actual project

=> so the question is. How can I get the cmake_mutli generators to work. The cmake conan docs [mention](https://github.com/conan-io/cmake-conan#cmake_build_type) a way to deal with cmake multi, however when searching for [conan_cmake_run()](https://github.com/conan-io/cmake-conan#conan_cmake_run-high-level-wrapper) there is a warning that this function is deprecated.

=>is this deprecated function still the only way to deal with multi config generators

**Comment by czoido** [comment]
Hi @Ju1He1,
There's a test using the new flow and testing a multi-generator approach with `cmake_find_package_multi` generator.
Please check it, I think it could help you:
https://github.com/conan-io/cmake-conan/blob/3530ac47930ce2d107becc1dd6c7f05b1103d130/tests.py#L991-L1012

**Comment by Ju1He1** [comment]
Hey Carlos,

thanks a lot that did work :)
