### ISSUE TITLE
Option to pass -u parameter to install

### ISSUE THREAD

**Issue by mikea** [conan-io/cmake-conan#40]
I'd like to pass a `--update` parameter to `conan install`. 
Should be either CONAN_UPDATE option or generic CONAN_INSTALL_OPTIONS argument to `conan_cmake_run`

**Comment by memsharded** [comment]
> CONAN_INSTALL_OPTIONS

Can you elaborate a bit more? Probably you want another argument, but not related to update?

**Comment by mikea** [comment]
I don't need to specify any other option but '-u' right now. I can imagine wanting to pass additional settings/options.

**Comment by memsharded** [comment]
Done, and pushed to master. When CI is finished I will tag a release.
