### ISSUE TITLE
Can't get a simple test going

### ISSUE THREAD

**Issue by coderalpha** [conan-io/cmake-conan#428]
Hi 

I've been trying to get a simple test going making use of the format library.

I added the following to my CMakeLists:

```cmake
conan_cmake_configure(REQUIRES fmt/8.1.1
    GENERATORS cmake_find_package)

conan_cmake_autodetect(settings)

conan_cmake_install(PATH_OR_REFERENCE .
                    BUILD missing
                    REMOTE conancenter
                    SETTINGS ${settings})
```

And then:
```cmake
find_package(fmt REQUIRED)
target_link_libraries(SimpleConan fmt::fmt)
```
Conan fetches the library, but find fails with the following error:

```
CMake Error at CMakeLists.txt:48 (find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.
```

However, I can see that **Findfmt.cmake** is generated in the build directory, and if I turn on **CMAKE_FIND_DEBUG_MODE**, I can see in the output that CMake finds it:
```
   Called from: [1]     /home/dev/Lab/SimpleConan/CMakeLists.txt
CMake Debug Log at CMakeLists.txt:48 (find_package):
  find_package considered the following paths for fmt.cmake

    /usr/share/cmake-3.22/Modules/Findfmt.cmake

  The file was found at

    ./Findfmt.cmake
```

I don't understand what is happening here.

Thanks.

**Comment by hwhsu1231** [comment]
I think you forgot to add the following two lines **before** `find_package()`:

```cmake
list(APPEND CMAKE_MODULE_PATH "${CMAKE_BINARY_DIR}")
list(APPEND CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}")
```

You have to tell `find_pacakge()` where to find `xxx-config.cmake` and `Findxxx.cmake` file.

**Comment by coderalpha** [comment]
Thanks for the tip, I have tried passing the module path and prefix path in as parameters to cmake, without success. I added the lines to the CMakeLists and that worked.

Thanks!
