### ISSUE TITLE
[suggest] Change the repository name into "conan-cmake".

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/cmake-conan#430]
As we can see, both the module file and commands defined in it are named with **"first `conan` then `cmake`"**. 

1.  The module file in this repository is `conan.cmake`.
2.  Lots of commands are named with `conan_cmake_xxx()`:

    - `conan_cmake_configure()`
    - `conan_cmake_autodetect()`
    - `conan_cmake_install()`
    - `conan_cmake_lock_create()`
    - `conan_cmake_run()`

However, I must to say that I sometimes wrote the command `conan_cmake_xxx()` wrong into `cmake_conan_xxx()`. It is because the name of repository, **"cmake-conan"**, is **"first `cmake` then `conan`"**. It confused me, sometimes.

Therefore, if the name of repository is changed into **"conan-cmake"**, it will avoid someone like me making the above-mentioned mistake.

**Comment by hwhsu1231** [comment]
By the way, I notice that:

- [conan-docker-tools](https://github.com/conan-io/conan-docker-tools)
- [conan-vs-extension](https://github.com/conan-io/conan-vs-extension)
- [conan-clion-plugin](https://github.com/conan-io/conan-clion-plugin)

All of these repositories are named with **"conan" as prefix**.

**Comment by czoido** [comment]
Hi @hwhsu1231,
Sorry, but I think that at the point we are now it's better to keep the current name so we don't have problems with the links to the repository and things like that. I think it would not be worth it.
Closing this. Thanks for the suggestion
