### ISSUE TITLE
Can cmake-conan support setting LD_LIBRARY_PATH during cmake procudure?

### ISSUE THREAD

**Issue by Tumb1eweed** [conan-io/cmake-conan#440]

**Comment by qknight** [comment]
@Tumb1eweed what would be your scenario? In general you should view conan builds as a closure, meaning, you give all the input as libraries, compiler, linker and get a library as output. If you need a LD_LIBRARY_PATH for one of your tools you could write a wrapper script which sets it and then just call the wrapper script instaed of the compiler/linker.
