### ISSUE TITLE
[question] Building using Emscripten and conan_cmake_run()

### ISSUE THREAD

**Issue by Bam4d** [conan-io/cmake-conan#466]
Hi, I've recently moved my codebase to using conan... but I'm having some problems setting up a wasm build.

Previously I would call `emcmake cmake .....` and `emmake make` to wrap the cmake/make. I assume that should happen automatically within conan if I add the build tool to my profile:

```
include(default)
[settings]
os=Emscripten
arch=wasm
compiler=clang
compiler.version=6.0
compiler.libcxx=libc++
[options]
[build_requires]
emsdk/3.1.23
[env]
```

I've then got a switch which uses a different conan file depending if im building with WASM or not:

```
if(WASM) 
        conan_cmake_run(
            CONANFILE ${GRIDDLY_DEPS_DIR}/${CONANFILE_WASM}
            CONAN_COMMAND ${CONAN}
            ${CONAN_EXTRA_REQUIRES}
            OPTIONS
            ${CONAN_EXTRA_OPTIONS}
            BASIC_SETUP
            PROFILE emsdk
            NO_OUTPUT_DIRS
            CMAKE_TARGETS # individual targets to link to
            KEEP_RPATHS
            BUILD missing
        )

    else()
        conan_cmake_run(
                CONANFILE ${GRIDDLY_DEPS_DIR}/${CONANFILE}
                CONAN_COMMAND ${CONAN}
                ${CONAN_EXTRA_REQUIRES}
                OPTIONS
                ${CONAN_EXTRA_OPTIONS}
                BASIC_SETUP
                NO_OUTPUT_DIRS
                CMAKE_TARGETS # individual targets to link to
                KEEP_RPATHS
                BUILD missing
        )
```

I tried following the answer to this question conan-io/conan#10259 ... but there seems to be no way to add the `--profile:build` or `--profile:host` options using `conan_cmake_run()`

Using just `PROFILE emsdk` here results in the same error as conan-io/conan#10259.

I've also tried `PROFILE_BUILD emsdk` alongside `PROFILE default`... but this results in another error:

```
ERROR: emsdk/3.1.23: 'settings.compiler' value not defined
```

It appears that the `default` option doesn't automatically detect the default options that it does if I dont specify a profile.

How (is it possible?) to do this using `conan_cmake_run()` ? 

I also I wanted to use `conan_cmake_profile()` from conan_cmake 0.19 but it's not been released yet. Is there a method of doing this in the current 0.18.1 version?

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
Moving this to the conan.cmake repo, as it seems specific about it.
If you want to simplify and reformulate the issue without conan.cmake (very recommended to know if it works without it, to see if it is a Conan issue or a conan.cmake issue), then we can bring it back here.

**Comment by Bam4d** [comment]
So after many more hours of fiddling I think I'm making progress but now the build cannot actually find the emscripten headers and they don't appear to be in the conan package....?

Now getting this error:
```
[path to repo]/Griddly/js/bindings/GriddlyJS.hpp:1:10: fatal error: emscripten/bind.h: No such file or directory
    1 | #include <emscripten/bind.h>
```

You can repeat the build steps/see full example of how im building this here: 
`https://github.com/Bam4d/Griddly/blob/wasm_fixies/js/build.sh`

If there's anything obvious that I'm doing wrong please let me know!

**Comment by Bam4d** [comment]
It looks like the headers are in another package, but I cannot see that package on conan...
https://github.com/emscripten-core/emscripten/blob/main/system/include/emscripten/bind.h

**Comment by Bam4d** [comment]
For some reason I think its not actually running the build() step (which downloads the bind.h file). Why might this be?

![image](https://user-images.githubusercontent.com/1370765/207393473-8539e360-4a69-4891-8fa2-784458040761.png)

**Comment by Bam4d** [comment]
OK so I've now refactored out the `conan_cmake_run` and am using the recommended configure -> autodetect -> install pattern which gets me much futher.

however now conan is failing to build one of the dependencies with the following error:
```
CMake Error: The source directory "/home/bam4d/.conan/data/spdlog/1.9.2/_/_/build/e909e723213829aee3c356fec5d465f5ea0eebd5" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
spdlog/1.9.2: 
spdlog/1.9.2: WARN: Package binary is corrupted, removing: e909e723213829aee3c356fec5d465f5ea0eebd5
spdlog/1.9.2: WARN: Build folder is dirty, removing it: /home/bam4d/.conan/data/spdlog/1.9.2/_/_/build/e909e723213829aee3c356fec5d465f5ea0eebd5
spdlog/1.9.2: ERROR: Package 'e909e723213829aee3c356fec5d465f5ea0eebd5' build failed
spdlog/1.9.2: WARN: Build folder /home/bam4d/.conan/data/spdlog/1.9.2/_/_/build/e909e723213829aee3c356fec5d465f5ea0eebd5
ERROR: spdlog/1.9.2: Error in build() method, line 98
```

**Comment by Bam4d** [comment]
Now got to the point where i builds the dependencies ok and then can't find them: 
![image](https://user-images.githubusercontent.com/1370765/207419040-361f2f9c-80ef-4c57-a198-3f51d10e5be9.png)

**Comment by Bam4d** [comment]
So I'm not entirely sure but I think that the `emsdk` module is not adding the includes directory that has all the emscripten headers. 

```
-- Build files have been written to: /home/bam4d/qmul/Griddly/build_wasm
Consolidate compiler generated dependencies of target griddlyjs
[  1%] Building CXX object CMakeFiles/griddlyjs.dir/js/bindings/GriddlyJS.cpp.o
In file included from /home/bam4d/qmul/Griddly/js/bindings/GriddlyJS.cpp:1:
/home/bam4d/qmul/Griddly/js/bindings/GriddlyJS.hpp:1:10: fatal error: emscripten/bind.h: No such file or directory
    1 | #include <emscripten/bind.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/griddlyjs.dir/build.make:93: CMakeFiles/griddlyjs.dir/js/bindings/GriddlyJS.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:88: CMakeFiles/griddlyjs.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

Everything else is all building fine after I updated to `configure -> autodetect -> install` pattern as recommended.

So I believe the emsdk build requires needs to be adding 
`.conan/data/emsdk/3.1.23/_/_/package/2880313eadc30db92089af7733fe8364772ee5c8/bin/upstream/emscripten/system/include` to the include dirs so that the header files can be grabbed, but I do not see this anywhere in any of the `conanbuildinfo` files.

if you can point me at how to fix this I will make a PR myself

**Comment by Bam4d** [comment]
Going to fix this by removing reliance on conan_cmake as its not compatible with the toolchain I need to use.

A basic example of the usage pattern can be found here:
https://github.com/Bam4d/conan-emscripten-test
