### ISSUE TITLE
Ability to use libstdc++11 with clang

### ISSUE THREAD

**Issue by r4zzz4k** [conan-io/cmake-conan#47]
I'm trying to switch from gcc to clang in a project built with CMake and Conan. One of my dependencies is `gtest/1.8.0@conan/stable`. As mentioned by @lasote [here](https://github.com/conan-io/conan/issues/1211#issuecomment-294424999) and in [this SO question](https://stackoverflow.com/questions/42162014/gtest-installed-with-conan-undefined-reference), I need to add `compiler.libcxx=libstdc++11` setting. Of course I can use global config or switch to proper conan usage instead of this project, but I'd like to stick to familiar `cmake && cmake --build` flow so that it's easier to use from IDE, especially for other devs etc.

I see there is a function called `conan_cmake_detect_gnu_libcxx`, which selects `libstdc++11` / `libstdc++` and is used for `GNU` compiler:
https://github.com/conan-io/cmake-conan/blob/930a63944e8721a30280c066ecfdc8bf0880a198/conan.cmake#L82-L83
But for `Clang` on non-Apple platforms `-s compiler.libcxx=libstdc++` is passed:
https://github.com/conan-io/cmake-conan/blob/930a63944e8721a30280c066ecfdc8bf0880a198/conan.cmake#L102-L104
Can we just use the same method here or more involved solution is needed? I didn't dive into the details, so I'm not sure if proposed change could break something.

**Comment by memsharded** [comment]
I am not sure, because ``conan_cmake_detect_gnu_libcxx`` checks for gcc flag ``_GLIBCXX_USE_CXX11_ABI`` which doesn't make much sense in clang. It also checks version against "5.1" to try to define libstdc++11 as the one being used.

So it might be necessary to add custom clang logic for this. I am fine with keeping ``_GLIBCXX_USE_CXX11_ABI`` as the flag to check if clangs ignores it.

**Comment by r4zzz4k** [comment]
Sorry, I managed to miss your answer and forgot about the issue for a bit.
From what I see in [libstdc++ documentation](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html), all `_GLIBCXX_` macros, including `_GLIBCXX_USE_CXX11_ABI`, are related to libstdc++, not to gcc toolchain. As clang also uses libstdc++, I believe it's okay to use mentioned macro to detect library version.

**Comment by memsharded** [comment]
Ok, got it, fixed it in #50, please have a look and report if necessary. Thanks!

**Comment by r4zzz4k** [comment]
Cool! I'll try to pull new config and rebuild the project tomorrow, but I've made same changes locally (sorry for not providing proper PR).
Thanks once again for your great efforts!

**Comment by memsharded** [comment]
Thanks to you for the feedback, don't worry!
It is on master branch, I haven't created a proper release/tag for it, but if everything looks good, I'll create a new one.
