### ISSUE TITLE
[suggest][dev2] Rename cmake-conan-specific variables with 'CMAKE_CONAN_' prefix .

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/cmake-conan#483]
### Suggestion

I noticed that ther are some cmake-conan-specific variables defined:

* `CONAN_OUTPUT_FOLDER`
* `CONAN_GENERATORS_FOLDER`
* ...etc

Since the environment variables provided by [Conan2 Docs](https://docs.conan.io/2/reference/environment.html) are named with `CONAN_` prefix, I suggest that cmake-conan rename its variables with `CMAKE_CONAN_` prefix in order to differentiate them. That is:

* `CMAKE_CONAN_OUTPUT_FOLDER`
* `CMAKE_CONAN_GENERATORS_FOLDER`
* ...etc

**Comment by memsharded** [comment]
Thanks for the suggestion, but this is not possible. ``CMAKE_`` variables are restricted to CMake itself, we cannot use that prefix.

**Comment by hwhsu1231** [comment]
Understood.
