### ISSUE TITLE
Boost with uppercase B is not found but boost with lowercase b is found

### ISSUE THREAD

**Issue by loic-lopez** [conan-io/cmake-conan#494]
Hi, 

I have recently upgraded my project to conan v2, when cmake and cmake-conan will try to resolve boost:
```cmake
find_package(Boost COMPONENTS program_options filesystem REQUIRED)
```
With the uppercase B it's says:
```bash
CMake Error at /home/myuser/cmake-3.26.1-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost: missing: program_options filesystem (found
  /mnt/d/Projects/Leaf/build/conan/build/Release/generators/BoostConfig.cmake
  (found version "1.81.0"))
Call Stack (most recent call first):
  /home/myuser/cmake-3.26.1-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:243 (_FPHSA_FAILURE_MESSAGE)
  /home/myuser/cmake-3.26.1-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:585 (_FPHSA_HANDLE_FAILURE_CONFIG_MODE)
  /home/myuser/cmake-3.26.1-linux-x86_64/share/cmake-3.26/Modules/FindBoost.cmake:626 (find_package_handle_standard_args)
  cmake/conan_support.cmake:185 (find_package)
  app/CMakeLists.txt:11 (find_package)
```

But this the lowercase B of 'boost'
```cmake
find_package(boost COMPONENTS program_options filesystem REQUIRED)
```

It resolve the boost path but display a warning :
```bash
CMake Warning (dev) at /home/myuser/cmake-3.26.1-linux-x86_64/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (Boost) does
  not match the name of the calling package (boost).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
```

I have read that conan 2 packages will only support lowercase packages name's  does it is related?

Thanks.

**Comment by memsharded** [comment]
Hi @loic-lopez 

Thanks for your report.

The ConanCenter ``boost`` package has been named lowercase since years. But the ``find_package()`` name and the CMake ``target`` are defined in the recipe to follow the upstream conventions, it is supposed to work.

Did you try without the cmake-conan v2 integration, just with ``conan install`` + ``cmake`` manually?

**Comment by loic-lopez** [comment]
> Hi @loic-lopez
> 
> Thanks for your report.
> 
> The ConanCenter `boost` package has been named lowercase since years. But the `find_package()` name and the CMake `target` are defined in the recipe to follow the upstream conventions, it is supposed to work.
> 
> Did you try without the cmake-conan v2 integration, just with `conan install` + `cmake` manually?

Like that?
```bash
conan install .
```

**Comment by loic-lopez** [comment]
> Hi @loic-lopez
> 
> Thanks for your report.
> 
> The ConanCenter `boost` package has been named lowercase since years. But the `find_package()` name and the CMake `target` are defined in the recipe to follow the upstream conventions, it is supposed to work.
> 
> Did you try without the cmake-conan v2 integration, just with `conan install` + `cmake` manually?

Before migrating to cmake-conan v2 integration I have used the v1 branch and the issue does not appears.

**Comment by memsharded** [comment]
Hi @loic-lopez 

I have been trying to reproduce this, but I didn't get the same results, I couldn't reproduce.
I used:

CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.24)
project(MyApp CXX)

set(CMAKE_CXX_STANDARD 17)
find_package(Boost REQUIRED)

add_executable(app main.cpp)
target_link_libraries(app boost::boost)
```
conanfile.txt:
```
[requires]
boost/1.81.0
```

And:
```bash
$ cmake .. -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=.....\conan_provider.cmake
...
boost/1.81.0: Full package reference: boost/1.81.0#8dcd9d9df9e0d320714b83cceddbe120:dd228bffcaf7a2c4edd2e867336606225916f436#d0fca399ef0c47fcf121b72f7fed15e2 
boost/1.81.0: Package folder C:\Users\memsharded\.conan2\p\boostdfc89be932331\p                                                                                    
boost/1.81.0: Disabled magic autolinking (smart and magic decisions)                                                                                          
WARN: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:                                                                               
WARN:     'env_info' used in: b2/4.9.3, boost/1.81.0, bzip2/1.0.8                                                                                             
WARN:     'cpp_info.names' used in: bzip2/1.0.8, zlib/1.2.13, boost/1.81.0                                                                                    
WARN:     'cpp_info.build_modules' used in: bzip2/1.0.8                                                                                                       
WARN:     'cpp_info.filenames' used in: boost/1.81.0                                                                                                          
WARN:     'user_info' used in: boost/1.81.0                                                                                                                   
                                                                                                                                                              
======== Finalizing install (deploy, generators) ========                                                                                                     
conanfile.txt: Writing generators to C:/Users/memsharded/conanws/cmake-conan/boosttest/build/conan                                                                 
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'                                                                                                     
conanfile.txt: Generating aggregated env files                                                                                                                
conanfile.txt: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']                                                                             
Install finished successfully                                                                                                                                 
-- CMake-conan: CONAN_GENERATORS_FOLDER=C:/Users/memsharded/conanws/cmake-conan/boosttest/build/conan                                                              
-- CMake-conan: find_package(Boost) found, 'conan install' aready ran                                                                                         
-- CMake-conan: find_package(ZLIB) found, 'conan install' aready ran                                                                                          
-- CMake-conan: find_package(BZip2) found, 'conan install' aready ran                                                                                         
-- Found Boost: C:/Users/memsharded/conanws/cmake-conan/boosttest/build/conan/BoostConfig.cmake (found version "1.81.0")                                                                                                                                                                                                  
-- Configuring done                                                                                                                                           
-- Generating done                                                                                                                                            
-- Build files have been written to: C:/Users/memsharded/conanws/cmake-conan/boosttest/build       
```
Maybe if you can post your output (the full one) that could help. Please make sure to use latest Conan 2.0.2.

**Comment by loic-lopez** [comment]
Conan version:
```bash
pc@pc:/mnt/d/Projects/Leaf/build$ conan -v
Conan version 2.0.2
```

In you example you have used:

```cmake
find_package(Boost REQUIRED)
```

but in my CMakeLists.txt I used find_package with the COMPONENTS directive
```cmake
find_package(boost COMPONENTS program_options filesystem REQUIRED)
```

And in the log above cmake is complaining that components are not found but boost have been found:
```cmake
Could NOT find Boost: missing: program_options filesystem (found
  /mnt/d/Projects/Leaf/build/conan/build/Release/generators/BoostConfig.cmake
  (found version "1.81.0"))
```

You can find my project based on conan : https://github.com/loic-lopez/Leaf/tree/feature/migrate_to_conan_2_0_2
The branch is `feature/migrate_to_conan_2_0_2`

**Comment by prince-chrismc** [comment]
Is there a particular reason you expect that component to exist?

Looking at the official cmake module file https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindBoost.cmake

That is not present and it's available under the headers target 🤔 


EDIT: that head variable is what they use to make components dynamically 

It's declared in the recipe too https://github.com/conan-io/conan-center-index/blob/e5e185ff47417265ff02529a09472dd79838b906/recipes/boost/all/dependencies/dependencies-1.81.0.yml#L21

**Comment by loic-lopez** [comment]
> Is there a particular reason you expect that component to exist?
> 
> 
> 
> Looking at the official cmake module file https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindBoost.cmake
> 
> 
> 
> That is not present and it's available under the headers target 🤔 
> 
> 
> 
> 
> 
> EDIT: that head variable is what they use to make components dynamically 
> 
> 
> 
> It's declared in the recipe too https://github.com/conan-io/conan-center-index/blob/e5e185ff47417265ff02529a09472dd79838b906/recipes/boost/all/dependencies/dependencies-1.81.0.yml#L21

I just need a few libraires of boost not the entire library.

**Comment by loic-lopez** [comment]
Hi, after upgrading the `conan_provider.cmake` file and upgrading conan to the latest version: `2.0.6` I am able to write again the boost find package with lowercase `b`

`find_package(boost COMPONENTS program_options filesystem REQUIRED)`

I don't know what changed but the issue is resolved.

Thanks all

**Comment by loic-lopez** [comment]
Hi, after upgrading the `conan_provider.cmake` file and upgrading conan to the latest version: `2.0.6` I am able to write again the boost find package with lowercase `b`

`find_package(boost COMPONENTS program_options filesystem REQUIRED)`

I don't know what changed but the issue is resolved.

Thanks all
