### ISSUE TITLE
Why did conan team release version 2.0 without upgrading packages?

### ISSUE THREAD

**Issue by igadmg** [conan-io/cmake-conan#497]
None of major packages we are using support version 2.0 - for example `qt`
So what was the point of releasing conan 2.0 if it just does not work anymore? Shouldn't it be in RC state still or have some support of 1.x packages?

**Comment by prince-chrismc** [comment]
This repository is to an auxiliary project and the team is hard at work updating this. See the develop 2 branch if you want to provide more helpful feedback.

Conan is so much more then just the packages that are provided, you can check ConanCenterIndex, there's a discussion with a lit of packages which were available at release. You can check issue 12888 with the 80% coverage of downloads list that was done during the betas.

Today there's well over 500 recipes migrated id estimate so I am sorry the few you need have not been migrated.

You are more then welcome to contribute to ConanCenter which is a community driven effort which the team supports!

**Comment by prince-chrismc** [comment]
All the packages in ConanCenter are still built and tested with 1.x so all 1500 are supported 👌 feel free to report bugs there!

I will close this issue since it's not technical in the sense of support or a bug. :)
