### ISSUE TITLE
[bug][dev2] detected host profile relies on default profile

### ISSUE THREAD

**Issue by melak47** [conan-io/cmake-conan#499]
I work on windows with MSVC primarily, so my default profile looks like:

```ini
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

If I now try to use the conan_provider.cmake in a build using MinGW-w64 GCC,
the automatically generated host profile looks like:

```ini
include(default)
[settings]
os=Windows
compiler=gcc
compiler.version=12
compiler.cppstd=17
build_type=Debug
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
```

The `include(default)` brings in incompatible settings like `compiler.runtime`, and is missing other required settings like `compiler.libcxx`.

**Comment by memsharded** [comment]
Thanks @melak47 for your report.

I think this would be a duplicate of https://github.com/conan-io/cmake-conan/issues/479, so maybe we can close this one and follow the other, which is already assigned to next iteration?

**Comment by melak47** [comment]
Ah, I did not see/connect that one.
