### ISSUE TITLE
How to use install packages build for gcc major versions?

### ISSUE THREAD

**Issue by bilke** [conan-io/cmake-conan#53]
`conan-package-tools` recently introduced gcc major versions (for gcc  version >= 5). How to use these? `cmake-conan` detects e.g. `compiler.version=5.4` but I want to use a package which was build with the `conangcc5`-docker image. Has `cmake-conan` to be adapted?

**Comment by memsharded** [comment]
No, you are right cmake-conan has not adapted yet. I'll have a look when possible, thanks for raising the issue!
