### ISSUE TITLE
What conan version does 0.18.0 support?

### ISSUE THREAD

**Issue by ksapozhn** [conan-io/cmake-conan#548]
Hi, my setup is:
CMake 3.27.1
conan 2.0.9
cmake-conan 0.18.0

When i try to do 
conan_add_remote(
    NAME name
    INDEX 0
    URL some_url
)

I get error code = 2

**Comment by kachsheev** [comment]
v0.18 is a stable branch, supports conan 1.x. I was testing with conan 1.59 and it worked correctly.

**Comment by ksapozhn** [comment]
Thanks! this solved my issue

**Comment by memsharded** [comment]
Note that the default branch in this repo is for Conan 1.X, but we already have quite advanced the integration for Conan 2.0 in the ``develop2`` branch. We might change the default branch soon, in principle it shouldn't affect if using a tag like 0.18.0, but just in case. In all cases, the recommendation is to prioritize the upgrade to Conan 2.0, it was released in February, and at some point ConanCenter will stop building packages for Conan 1.X.
