### ISSUE TITLE
conan.cmake does not respect settings from profile

### ISSUE THREAD

**Issue by lbakman** [conan-io/cmake-conan#57]
I can see that in the master branch as of 12 hours ago, conan.cmake does not respect the compiler.libcxx setting from the profile if using GCC as your compiler (conan.cmake line 88).

Is this the intended behaviour?

I have set compiler.libcxx to libstdc++ in my profile, but conan insists on using libstdc++11 anyway when compiling. I am using MingW w64 gcc version 7.1.

Edit: Ok, not exactly sure it was the change from 12 hours ago, but I just had this problem now and I downloaded the conan.cmake file several times yesterday and did not have the problem...

Edit again: Still on conan 0.30.3

Regards
Lau Bakman

**Comment by memsharded** [comment]
Hi Lau!

I think the settings were never meant to be used from profiles, as cmake controls its own definition of compiler, architecture, etc. Profile usage is mainly to complement other features (options, build_requires, env-vars).

In which branch of cmake-conan are you running? Master, develop? If you want stable behavior and controlled updates, I think you might want to use tagged releases of this repo, they are regularly published.

If you check the code you will see that the definition of the libcxx is not controlled by the setting, but by the var ``_GLIBCXX_USE_CXX11_ABI``. I think this behavior was from very early. You can control which libcxx are you using by setting it to 1 or 0

Please try and tell me. Thanks!

**Comment by lbakman** [comment]
My apologies, I realise that the above issue description is nowhere near complete.

I am using conan 0.30.3 and I am downloading conan.cmake from the master branch every time I delete my build directory. So far this has worked like a charm, and it still does. 

I was surprised today because all of my dependencies started to rebuild, and the one thing that caught my eye was the difference in compiler.libcxx from my default profile. I have tried with a version of conan.cmake from last week, and it turns out that the reason for the rebuild was not the change in compiler.libcxx but because the compiler version went from MAJOR.MINOR to just MAJOR.

There was nothing wrong. Next time I will investigate a bit more before raising an issue.

Thanks!

**Comment by memsharded** [comment]
No problem at all!!
Much better to raise an issue, that at the end is a false positive, than not saying anything and let a real issue affect other users. So thanks for submitting the issue.

Yes, we have changed the default version for GCC to match the new version policies of GCC itself, that are now using minors for bug fixes, so they are ABI compatible and the default of using only the major should be ok for most cases.

Cheers!
