### ISSUE TITLE
Equivalent command of conan_cmake_configure in conan 2.x

### ISSUE THREAD

**Issue by laxmij-cmd** [conan-io/cmake-conan#572]
### What is your question?

Hi,

In conan 1.x I was using conan_cmake_configure to generate conanfile.txt at runtime. what is it's equivalent command in cona n2.x?

Best Regards

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment]
This is a question about cmake-conan integration, moving it there.

**Comment by memsharded** [comment]
Hi @laxmij-cmd 

Thanks for your question. You can find the new cmake-conan integration for Conan 2.0 in the ``develop2`` branch in: https://github.com/conan-io/cmake-conan/tree/develop2

This integration is based on the new CMake dependency providers, that allow fully transparent integration. No modifications at all in your ``CMakeLists.txt`` are required, please check the quick start in the readme https://github.com/conan-io/cmake-conan/tree/develop2#quickstart-with-conan-20, feedback about the new integration welcome.

**Comment by laxmij-cmd** [comment]
Thanks!
