### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK on downloading conan.cmake

### ISSUE THREAD

**Issue by smasihemami** [conan-io/cmake-conan#575]
Hi,
We are getting 'SSL peer certificate or SSH remote key was not OK' on downloading conan.cmake through the following cmake snippet, could you please advise on potential workarounds:

if (NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/0.18.1/conan.cmake"
        "${CMAKE_BINARY_DIR}/conan.cmake"
        TLS_VERIFY ON
        STATUS DOWNLOAD_STATUS)
endif ()

list(GET DOWNLOAD_STATUS 0 STATUS_CODE)
if (0 EQUAL ${STATUS_CODE})
    message(STATUS "Downloaded conan.cmake successfully to ${CMAKE_BINARY_DIR}/conan.cmake")
else ()
    message(STATUS "Something went wrong when downloading conan.cmake to ${CMAKE_BINARY_DIR}/conan.cmake, error ${DOWNLOAD_STATUS}")
endif ()

**Comment by memsharded** [comment]
Hi @smasihemami 

This snippet is doing a download from Github directly, so I am afraid that it is a bit outside of our control.
Typical reasons would be some company VPN, proxy, ZScaler or similar that could be blocking you, and you might need to contact IT.

As possible workarounds, there is a very easy one, download the ``cmake-conan`` from the repo and put it in your repo. This will be the recommended approach anyway in Conan 2.0, where the new ``cmake-conan`` integration is using the new CMake dependency providers and thus is fully transparent, it doesn't need to modify the CMakeLists.txt at all.
