### ISSUE TITLE
Allow passing NO_OUTPUT_DIRS to conan_cmake_run

### ISSUE THREAD

**Issue by koliyo** [conan-io/cmake-conan#60]
`conan_cmake_run` calls `conan_basic_setup` which has a [NO_OUTPUT_DIRS](http://docs.conan.io/en/latest/reference/generators/cmake.html#conan-basic-setup) setting.

But this can not be set using the `conan_cmake_run` function

**Comment by memsharded** [comment]
Yes, this is possible. 
As a workaround you can not pass BASIC_SETUP to ``conan_cmake_run``, and then use explicitly ``conan_basic_setup(NO_OUTPUT_DIRS ....)`` after it.
