### ISSUE TITLE
[develop2][Question] Is it possible to set the build policy to never?

### ISSUE THREAD

**Issue by maximiliank** [conan-io/cmake-conan#601]
Currently, `conan install` is run with `--build=missing`, see

https://github.com/conan-io/cmake-conan/blob/c53fbf58e4afe7cb93cb32e730d6647fc47a5dce/conan_provider.cmake#L520

Is there a possibility to set this to `never` via cmake preset entry? I want to disable building missing packages in the CI preset and enforce to use only existing compiled version of the package. If there is a missing package the job in the CI should fail instead of rebuilding the library on every run.

**Comment by memsharded** [comment]
Hi @maximiliank 

Thanks for your question.
Well, at the moment there is no user configuration for this argument, though we might be considering it.

Just in case, the ``conan_provider.cmake``, at the end of the day is a file that goes in your repo, so it should be very easy to customize it and just remove the ``--build=missing`` in it, isn't it?

**Comment by maximiliank** [comment]
Hi @memsharded

you are absolutely right, the easiest is to adjust the script in the repo. Thank you for pointing this out.
