### ISSUE TITLE
[develop2] Question: How stable is the current state

### ISSUE THREAD

**Issue by ghost** [conan-io/cmake-conan#616]
Hey guys,
I'm using cmake-conan to invoke conan from cmake.
With latest conan 1.x I'm getting more and more "conan 1.x deprecation warnings".
I'd like to migrate to conan 2.x
So my question is: How stable is the current state of cmake-conan. Is there an initial release planed?

**Comment by memsharded** [comment]
Hi @Ju1He1 

The ``cmake-conan`` integration is being used already in the CLion plugin, and it seems to be working well. We have also tried to not break anything in the latest changes and improvements, so I'd say that overall is more or less same stable as the previous Conan 1.X. We will soon start to give it more official versions and make some announcement.

In any case, the recommended way to use the ``conan_provider.cmake`` is to do a copy in your project. That, together with the fact that the main ``CMakeLists.txt`` shouldn't be modified to add anything related to Conan, should make it probably even more stable than the 1.X version in practice.

**Comment by ghost** [comment]
@memsharded  thx for the clarification. That's good to hear. I'll be waiting for an official release then :)
