### ISSUE TITLE
License and other information inside the conan.cmake file

### ISSUE THREAD

**Issue by Pancir** [conan-io/cmake-conan#62]
Hello there, I want to suggest you to write the license information at the top of the conan.cmake file because this file can be saved into people own repositories. 
Also it is good idea to write after the license information what this file is for,  it will help some developers to understand this file, for example when this file is auto-downloaded with cmake and a developer sees a new file in his repository he can just open it and read information what this file is for.
Thank you.

**Comment by memsharded** [comment]
Good point, submitted PR #63 with it
Thanks for the suggestion!

**Comment by memsharded** [comment]
Released in https://github.com/conan-io/cmake-conan/releases/tag/v0.9. Thanks!
