### ISSUE TITLE
"ERROR: Conanfile not found!" in latest version (reason included)

### ISSUE THREAD

**Issue by Zoodinger** [conan-io/cmake-conan#65]
Hello,

I tried to do a clean build and it was failing. I found that the error was in the latest version of conan.cmake. It crashes with the message:
```
ERROR: Conanfile not found!
CMake Error at cmake-build-debug/conan.cmake:265 (message):
  Conan install failed='1'
```

I did a diff on the files and found the change that broke my configuration.

Line 235 was changed from:
```
set(CONANFILE -f=${CMAKE_CURRENT_SOURCE_DIR}/${ARGUMENTS_CONANFILE})
```
to:
```
set(CONANFILE ${CMAKE_CURRENT_SOURCE_DIR}/${ARGUMENTS_CONANFILE})
```

I don't know what the significance of `-f=` is, but restoring it makes everything work as before.

Thanks for all your work!

Zoodinger

**Comment by Zoodinger** [comment]
Well, as it turns out it looks like this change was made to accommodate the breaking changes in the newest release of Conan. After upgrading, it now works only without `-f=`.

**Comment by memsharded** [comment]
Yes, exactly.

There were tagged releases, as instructed in the docs the idea if you were using 0.30.3 is it wouldn't break if you were using the latest tagged release of cmake-conan

In any case, yes, it is much better to upgrade conan to 1.0. Thanks for the feedback!
