### ISSUE TITLE
[bug] passing path with ""(double quotes) to conan_install()

### ISSUE THREAD

**Issue by forry** [conan-io/cmake-conan#658]
Hello,
using cmake-conan deps provider I have my fork where I want to use deployers so I'm adding a couple more args to conan_install macro in conan_provide_dependency. It looks like this:
```cmake
conan_install(${_host_profile_flags} ${_build_profile_flags} -s build_type=Debug ${CONAN_INSTALL_ARGS} ${generator} ${deployers_arg} "--deployer-folder=\"${CMAKE_BINARY_DIR}/bin/${_config}\"")
```
then the output in the conan_install shows
```
CMake-Conan: conan install D:/lexocad/repo -of=D:/lexocad/build_conan2/generators --profile:host=default;--profile:host=D:/lexocad/build_conan2/conan_host_profile;--profile:build=default;-s;build_type=Release;--build=missing;--deployer="D:/lexocad/repo/cmake/lx_deployer.py";--deployer-folder="D:/lexocad/build_conan2/bin/Release"
```
which seems correct and those double quotes around the path need to be there in case there is a space in a folder name (or a deployer filename - I have tried that and it fails without them)
Then the conan.exe fails with:
```
ERROR: Traceback (most recent call last):
  File "D:\lexocad\conan2_test\conan2env\Lib\site-packages\conan\cli\cli.py", line 291, in main
    cli.run(args)
  File "D:\lexocad\conan2_test\conan2env\Lib\site-packages\conan\cli\cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "D:\lexocad\conan2_test\conan2env\Lib\site-packages\conan\cli\command.py", line 165, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lexocad\conan2_test\conan2env\Lib\site-packages\conan\cli\commands\install.py", line 75, in install
    conan_api.install.install_consumer(deps_graph, args.generator, source_folder, output_folder,
  File "D:\lexocad\conan2_test\conan2env\Lib\site-packages\conan\api\subapi\install.py", line 80, in install_consumer
    do_deploys(self.conan_api, deps_graph, deploy, deploy_package, base_folder)
  File "D:\lexocad\conan2_test\conan2env\Lib\site-packages\conan\internal\deploy.py", line 43, in do_deploys
    mkdir(deploy_folder)
  File "D:\lexocad\conan2_test\conan2env\Lib\site-packages\conans\util\files.py", line 247, in mkdir
    os.makedirs(path)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'D:\\lexocad\\build_conan2\\"D:'
```
I've done some poking though I'm not a python programmer. **That's why the line 80 in the install_consumer is incorrect**. Original line is 78. I have added some debugging output to find out the reason. The quotes are not parsed out and get into the os.path.abspath(deploy_folder) here:
```python
   if deploy or deploy_package:
            # Issue related: https://github.com/conan-io/conan/issues/16543
            base_folder = os.path.abspath(deploy_folder) if deploy_folder \
                else conanfile.folders.base_build
            do_deploys(self.conan_api, deps_graph, deploy, deploy_package, base_folder)
```
This gets `os.path.abspath("\"D:/lexocad/build_conan2/bin/Release\"")` which results in the incorrect string output.

I'm not really sure if this is a conan or cmake-conan problem. But from cmake's perspective, those quotes are really necessary as I've said. But I also know that when I issue that command from the powershell with those quotes it runs fine. So maybe the fix need to be in conan itself. Note that the same problem is with the --deployer arg, which is resolved later, and the deploy variable in the `install_consumer` has a value of: `['"D:/lexocad/repo/cmake/lx_deployer.py"']`.

CMake 3.29.5
python 3.12.4
conan 2.5.0
cmake-conan eba63de9 from 07/02/2024

**Comment by memsharded** [comment]
Hi @forry 

Thanks for your report.

I have been able to reproduce using only the Conan with:
```
conan install --requires=zlib/1.3.1 --deployer=full_deploy --deployer-folder="\"mydeployy\""
````

That means that the argument value is getting an extra quote, that is not expected, and makes it fail. I can try to raise a better error message (now it is raising an exception with a traceback), but from the Conan client point of view, it is expected to fail.

**Comment by forry** [comment]
That is nice, but how do you suggest I supply that from cmake-conan if my folder path is e.g. `C:\Path with a space\target folder`?

**Comment by forry** [comment]
My bad, I need to put those quotes around the whole argument and I don't need them just around the Path.

Thanks and sorry! I thought that I tried that combination.

**Comment by memsharded** [comment]
No prob! Thanks for the report anyway.

I have submitted https://github.com/conan-io/conan/pull/16723 to improve a bit the error message when this happens.
