### ISSUE TITLE
conan.cmake and conan disagrees on compiler version

### ISSUE THREAD

**Issue by ibbles** [conan-io/cmake-conan#66]
Ubuntu 17.10
GCC 7.2
Conan 1.0.2

Packages I build are tagged with compiler version "7.2", but `conan.cmake` will only accept packages with compiler version exactly "7". I believed, based on https://github.com/conan-io/conan/issues/1214, that version "7.2" is-a version "7" and that the "7.2" package should be used.

More detailed information follows.

When I build packages they get marked with compiler version 7.2. For example:
```
➤ conan search lua/5.1.4@ibbles/stable
Existing packages for recipe lua/5.1.4@ibbles/stable:

    Package_ID: b2fcd8dec3b6100295f93388a49eba2a7d69f5a0
        [options]
            shared: True
        [settings]
            arch: x86_64
            compiler: gcc
            compiler.version: 7.2
            os: Linux
        outdated from recipe: False
```

In the client project we have a `conanfile.txt` with the following content:
```
➤ cat conanfile.txt 
[requires]
lua/5.1.4@ibbles/stable

[generators]
cmake
```

We use `conan.cmake` as follows

```
include(${CMAKE_SOURCE_DIR}/conan.cmake)

conan_cmake_run(CONANFILE conanfile.txt
    BASIC_SETUP
    CMAKE_TARGETS
    BUILD ${AGX_CONAN_BUILD_RULE}  # Set to 'all' to force rebuild of dependencies.
)

conan_flags_setup()
```

CMake fails with the following error message:

```
lua/5.1.4@algoryx/stable: WARN: Can't find a 'lua/5.1.4@ibbles/stable' package for the specified options and settings:
- Settings: arch=x86_64, compiler=gcc, compiler.version=7, os=Linux
- Options: shared=True
```

conan.cmake contains the following:
```
set(COMPILER_VERSION ${MAJOR}.${MINOR})
if(${MAJOR} GREATER 4)
    set(COMPILER_VERSION ${MAJOR})
endif()
```

If I comment out the `if` block then I get the package I expect.

Is this expected behavior? If so, what should I do to be able to use my packages in my client application?

**Comment by sixten-hilborn** [comment]
Yes this is intended since Conan 1.0. Minor versions of gcc are binary compatible since gcc 5, so this was fixed in conan 1.0.
It's recommended to upgrade conan and rebuild the package with compiler.version=7

**Comment by ibbles** [comment]
I'm already using Conan 1.0.

Did some more reading and experimentation and my current theory is that the upgrade from 0.30 to 1.0 missed to update `.conan/profiles/default`, which still had `compiler.version=7.2`. Therefore all packages  were still created with 7.2. I fixed it by deleting `.conan/profiles/default`, which caused Conan to recreate it on the next `conan create`. This time I got a `.conan/profiles/default` with `compiler.version=7` and everything works as expected.

**Comment by memsharded** [comment]
Yes, that was a complicated decission but we finally decided not to modify users ``default`` profile, as it would be a bit intrussive and break things. So users need to be aware and update their profiles.

I am going to add at least a section in the "Upgrading to 1.0" in the docs.
