### ISSUE TITLE
[develop2]How to enable build_type switch after cmake executed with Multi Configuration generators like Visual Studio?

### ISSUE THREAD

**Issue by followtheart** [conan-io/cmake-conan#663]
Asking for help.

Using `conan_provider.cmake` as recommended like:
```
$cmake_args += " -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=$source_root\conan_provider.cmake"
$cmake_args += " -DCMAKE_BUILD_TYPE=Release"
```

and got `conan/build/generators/xxx-config.cmake` ONLY ***RELEASE*** version configed ,like :
```
########## MACROS ###########################################################################
#############################################################################################

# Requires CMake > 3.15
if(${CMAKE_VERSION} VERSION_LESS "3.15")
    message(FATAL_ERROR "The 'CMakeDeps' generator only works with CMake >= 3.15")
endif()

if(xxx_FIND_QUIETLY)
    set(xxx_MESSAGE_MODE VERBOSE)
else()
    set(xxx_MESSAGE_MODE STATUS)
endif()

include(${CMAKE_CURRENT_LIST_DIR}/cmakedeps_macros.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/xxxTargets.cmake)
include(CMakeFindDependencyMacro)

check_build_type_defined()

foreach(_DEPENDENCY ${xxx_FIND_DEPENDENCY_NAMES} )
    # Check that we have not already called a find_package with the transitive dependency
    if(NOT ${_DEPENDENCY}_FOUND)
        find_dependency(${_DEPENDENCY} REQUIRED ${${_DEPENDENCY}_FIND_MODE})
    endif()
endforeach()

set(xxx_VERSION_STRING "1.0.0")
set(xxx_INCLUDE_DIRS ${xxx_INCLUDE_DIRS_RELEASE} )
set(xxx_INCLUDE_DIR ${xxx_INCLUDE_DIRS_RELEASE} )
set(xxx_LIBRARIES ${xxx_LIBRARIES_RELEASE} )
set(xxx_DEFINITIONS ${xxx_DEFINITIONS_RELEASE} )

# Only the last installed configuration BUILD_MODULES are included to avoid the collision
foreach(_BUILD_MODULE ${xxx_BUILD_MODULES_PATHS_RELEASE} )
    message(${xxx_MESSAGE_MODE} "Conan: Including build module from '${_BUILD_MODULE}'")
    include(${_BUILD_MODULE})
endforeach()
```

which installed by
https://github.com/conan-io/cmake-conan/blob/8bf396b92f37f8942d0be24453e8aa268d61ecba/conan_provider.cmake#L590-L594

There are also other build_type config files generated,like:
```
xxx-Target-debug.cmake
xxx-Target-release.cmake
xxx-Target-relwithdebinfo.cmake
```
But,When build the solution `xxx.sln` with Visual Studio,and choose a build_type `debug`(not same with `$cmake_args += " -DCMAKE_BUILD_TYPE=Release"`),Got errors like:
```
error C1083 Cannot open include file: “xxx.h”: No such file or directory
```
And my problem is:how to enable build_type switch after cmake executed with multi configuration generators like Visual Studio?
Thx a lot.

**Comment by jcar87** [comment]
The file which is included by this line `include(${CMAKE_CURRENT_LIST_DIR}/xxxTargets.cmake)` should include both the `xxx-Target-debug.cmake` and `xxx-Target-release.cmake` files -
this should make it work.

In this instance I dont think you need to reconfigure the CMake tree again - just generate it once, which will cause Conan to generate targets for both Debug and Release, and choose the visual studio toggle.

Do you have any specific library where this isn't working? 

I'm unable to reproduce this with the example included in develop2 - on Windows:

```
cd cmake-conan/example
mkdir build
cmake -B build -S . -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES="../conan_provider.cmake" -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release
cmake --build build --config Debug
```

Alternatively instead of calling `cmake --build` you can open the sln and build both configurations:

```
start ./build/FormatOutput.sln
```

both builds succeed:
```
(venv) example> .\build\Release\main.exe
Hello fmt 90100!
(venv) example> .\build\Debug\main.exe
Hello fmt 90100!
```

**Comment by followtheart** [comment]
Thx for your reply.It seems you're correct.
The error:
```
error C1083 Cannot open include file: “xxx.h”: No such file or directory
```
is caused by my mistake of using
```
target_link_libraries(${target}  libxxxx)
```
but it seems only targets like `libxxxx::libxxxx` registered and can been recognized by conan/cmake,eg:
```
target_link_libraries(${target}  libxxxx::libxxxx )
```
And this triggers headers auto included,and fix my problem.Nothing about build_type...

Thx again.
