### ISSUE TITLE
Clang 19 not supported in the default ~/.conan2/settings.yml

### ISSUE THREAD

**Issue by AndreaCicca** [conan-io/cmake-conan#672]
I have installed the latest version of clang and it is not supported by the default yaml settings

> ERROR: Invalid setting '19' is not a valid 'settings.compiler.version' value.
Possible values are ['3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '4.0', '5.0', '6.0', '7.0', '7.1', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18']
Read "http://docs.conan.io/2/knowledge/faq.html#error-invalid-setting" 

llvm's documentation related to the [release](https://releases.llvm.org/19.1.0/tools/clang/docs/ReleaseNotes.html) of Clang 19

**Comment by AndreaCicca** [comment]
My bad, I did update Conan to the latest version

**Comment by memsharded** [comment]
https://github.com/conan-io/conan/pull/17010 added support for clang 19 in the default settings.yml, this will be in Conan 2.8.

In the meantime, you can add it to your default ``settings.yml`` or define it in ``settings_user.yml``

**Comment by AndreaCicca** [comment]
Thanks
