### ISSUE TITLE
Conan 2.x CLion Migration - Manual cmake-conan Install Necessary?

### ISSUE THREAD

**Issue by radonish** [conan-io/cmake-conan#679]
Hello,
I'm working on migrating my company to Conan 2.x. After successfully getting our packages migrated to Conan 2.x and building via command line (via `conan create` both manually and in Jenkins pipelines) I've moved on to the developer use case of opening package projects in CLion and being able to build/debug within the IDE.

I posted some Conan Plugin [questions](https://github.com/conan-io/conan-clion-plugin/issues/217) within the plugin repo but wanted to confirm whether or not I needed to manually install cmake-conan. I assumed I did *not* need to install it because on first attempt with the CLion Conan plugin I saw the conan_provider.cmake file generated - it appeared like perhaps it was packaged with Conan.

If I'm using Conan 2.10.0, do I have the latest version of this cmake-conan utility or do I need to install it separately?

Thanks!

**Comment by memsharded** [comment]
Hi @radonish 

Thanks for your question.

The CLIon plugin might generate the ``conan_provider.cmake`` on the fly if missing. But in general, that file would need to be put in the project, typically manually and it can be committed to git, so developers can do ``git clone`` + ``cmake --preset`` (the preset defines the provider already) easily, without even using the IDE

**Comment by radonish** [comment]
Hello @memsharded, thanks for your response. I was able to confirm that the CLion Conan Plugin is generating the `conan_provider.cmake` file. I also verified that the file matches the latest version of the cmake-conan repo so I should be good to go. Thanks!
