### ISSUE TITLE
conan.cmake should be versioned

### ISSUE THREAD

**Issue by reidhoch** [conan-io/cmake-conan#7]
As a user I'd like to be able to download a versioned (e.g v0.5) conan.cmake file. If I'm always downloading from `master` the file I download may silently change between builds.

**Comment by memsharded** [comment]
Yes, sounds reasonable. Tagging the repo could be enough I guess?
So far, I didn't do it, because I feel still quite unstable, so I'd prefer all users moving always forward from ``master``, but if you think it could already be done, no problem.

**Comment by reidhoch** [comment]
I think tagging is enough. I agree it feels early and unstable, I'm using it in a few development branches right now with success. Before merging to `master` though I'd like to know that I'm always getting the same file between CI builds.

**Comment by memsharded** [comment]
Ok, I have started adding tags: https://github.com/conan-io/cmake-conan/releases/tag/v0.1-alpha

You can now refer to them, to be sure it will not be changed between builds. I will generate more tags as improvements are done to the repo, just check the releases page.

Cheers!
