### ISSUE TITLE
Allow setting build type to conan_cmake_settngs and conan_cmake_run

### ISSUE THREAD

**Issue by bc-lee** [conan-io/cmake-conan#71]
In CMake, `CMAKE_BUILD_TYPE` is not restricted to `("Debug", "Release")`, but it can have arbitrary string value, like RelWithDebInfo or DebugAsan or so on. Moreover, Conan profile can have various build_type by modifying `settings.yml`.

So it's a good idea to have the ability to set build_type in `conan_cmake_settings` and `conan_cmake_run`.  I have a working patch for it, but I'll wait submit it until merging #70 since it is quite similar patches.

**Comment by memsharded** [comment]
This has been implemented (with a new test) in https://github.com/conan-io/cmake-conan/releases/tag/v0.9. Please have a look and report if possible, or close the issue if fixed. Thanks!

**Comment by bc-lee** [comment]
It works pretty well. Thanks!
