### ISSUE TITLE
Definitions and strings with spaces

### ISSUE THREAD

**Issue by atvise** [conan-io/cmake-conan#82]
Hi,

first of all I want to thank you for conan, it's an unbelievable life saver and awesome product ;) !

is there any way how I can use strings with spaces in definitions f.e.:

`self.cpp_info.defines["MY_DEF"] = "My string"`

Because if I use this kind of assignment this will be created:

`-DMY_DEF="My string"`

When I want to use this package in an CMake project an CMake error occurs:

"Argument not separated from preceding token by whitespace."

When I edit the "conanbuildinfo.cmake" file from:

`set(CONAN_DEFINES -DMY_DEF="My string")`

to:

`set(CONAN_DEFINES "-DMY_DEF=\"My string\"")`

everything works fine.

I'm would very appreciating any help in that matter!

My system info:
conan version: 1.2.0
CMake version: 3.11.0
Os version: Win 10 x64
Python version: 2.7.14

**Comment by memsharded** [comment]
Hi @atvise !

> first of all I want to thank you for conan, it's an unbelievable life saver and awesome product ;) !

Thanks for your kind words :)

I am not sure about your syntax, as stated in http://docs.conan.io/en/latest/reference/conanfile/methods.html#package-info, the defines are a list of definitions. I would expect your definition to be something like:

```python
self.cpp_info.defines= ['MY_DEF="My string"']
```
Could you please check it? 

Recently some support for escaping cmake strings was added in: https://github.com/conan-io/conan/pull/2555/files, maybe it has to be be somehow extended to defines too.

**Comment by atvise** [comment]
Hi @memsharded,

> I would expect your definition to be something like:

Sry my bad i'm actually already using this syntax. I've had written this issue out of my memory.
That means the mentioned problems still nevertheless occur.

Thx for your help!

**Comment by memsharded** [comment]
I have done a small test, with a "Tool" conanfile.py containing:

```python
    def package_info(self):
        self.cpp_info.defines= ['MY_DEF="My string"', 'MY_DEF2="My other string"']
```

And then a "Hello" package depending on "Tool" with a library containing source code:
```cpp
#include <iostream>
#include "hello.h"
#define STRINGIFY(x) #x
#define STRINGIFYMACRO(y) STRINGIFY(y)

void hello(){
    std::cout << "Msg1: " << STRINGIFYMACRO(MY_DEF) << "\n";
    std::cout << "Msg2: " << STRINGIFYMACRO(MY_DEF2) << "\n";
}
```

It works well, the conanbuildinfo contains:
```cmake
set(CONAN_DEFINES_TOOL -DMY_DEF="My string"
			-DMY_DEF2="My other string")
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_TOOL MY_DEF="My string"
			MY_DEF2="My other string")
```
Which seems to parse well, and the test application build and runs successfully:
```bash
Msg1: "My string"
Msg2: "My other string"
```

Now I see the issue. The thing is that you would like to have those strings without the extra quotes. Yes, confirmed this is an issue, will try to solve it. Thanks for the feedback!

**Comment by memsharded** [comment]
Ey, but this is an issue for conan, not for cmake-conan! :)

I will move the issue there.
