### ISSUE TITLE
How to make set certain environment variables for the conan execution?

### ISSUE THREAD

**Issue by trivigy** [conan-io/cmake-conan#83]
My issue is that I need to compile boost with BOOST_ASIO_NO_DEPRECATED but the official community conan package for boost 1.67 does not support setting this as an option. Is there a way for me to set this as an environment variable via conan_cmake_run()? I know I could use profiles by setting `[env]` and setting it in a profile but that feels like an overkill that I want to try and avoid.

**Comment by memsharded** [comment]
Hi @trivigy 

I am having a look at this issue, considered to add it for 0.13 release. But wondering, if you want to set an env-var, you can directly set it as you wish from your CMakeLists.txt, with ``set(ENV{...})``. Am I missing something?

**Comment by trivigy** [comment]
@memsharded thank you for responding to this. I really don't remember what the issue was here since I moved on from this so long ago. I am just going to close this issue.

**Comment by memsharded** [comment]
Ok, good. In any case, for reference, ENV argument has been added to ``cmake_conan_run()`` in conan 0.13.
Thanks for following up.
