### ISSUE TITLE
Unable to build packages using Clang with libc++ on Linux.

### ISSUE THREAD

**Issue by l90lpa** [conan-io/cmake-conan#84]
In the conan.cmake file in the `conan_cmake_settings` function, when it checks the compiler ID, if the compiler is `Clang` (checked at line 145) and if the environment is not `APPLE` the fucntion `conan_cmake_detect_gnu_libcxx` is called. Inside this function it only ever sets the STL library to either `libstdc++11` or `libstdc++`. Because of this the conan packages cannot be built with Clang using the libc++ STL implementation on Linux.

**Comment by l90lpa** [comment]
Hello, I've just noticed the new `SETTINGS` option for `conan_cmake_run()`. Is it recommended to use this to set the particular compiler.libc++ setting? I'm asking because this will populate the `_SETTINGS` variable with two instances setting compiler.libcxx e.g. "-s compiler.libcxx=libstdc++ ... -s compiler.libcxx=libc++". Is it the intended behaviour of `conan install` to use the last value specified?

**Comment by memsharded** [comment]
Hi @l90lpa 

Not, it is not intended to use the last value, I think cmake-conan should avoids its repetition, this might need fixing. Thanks for reporting it!

**Comment by memsharded** [comment]
I am having a look. What would be the "standard" CMake approach for defining the usage of libc++ in Linux-Clang? The idea of ``conan_cmake_settings`` is that it automatically extracts the settings from the current CMake configuration, so it would be great to know if such configuration exists for libc++.

**Comment by Artalus** [comment]
At first I was rather surprised that the wrapper doesn't look into Conan profile for `compiler.libcxx` value. Then I thought that the main problem with this approach would be - what if user wants to use some other profile than `default`?

Clearly specifying `libcxx` or profile name somewhere in `CMakeLists.txt` would be a bad move for anything that is intended to build outside of strictly set environment. Maybe `conan.cmake` should take into account the values of some other CMake variables, like `conan-package-tools` do with envvars?

In this case, if I call CMake from terminal, I could go `cmake -DCMAKE_CONAN_LIBCXX=libc++ ..`, and when using CMake in Qt Creator with my predefined Kit I could also specify additional variables in the Kit itself.
