### ISSUE TITLE
Failure in conan_cmake_detect_vs_runtime if BUILD_TYPE argument is passed

### ISSUE THREAD

**Issue by L-M-V** [conan-io/cmake-conan#89]
conan_cmake_settings successfully handles the argument with the following code:
```
    if(ARGUMENTS_BUILD_TYPE)
        set(_SETTINGS ${_SETTINGS} -s build_type=${ARGUMENTS_BUILD_TYPE})
    elseif(CMAKE_BUILD_TYPE)
        set(_SETTINGS ${_SETTINGS} -s build_type=${CMAKE_BUILD_TYPE})
    else()
        message(FATAL_ERROR "Please specify in command line CMAKE_BUILD_TYPE (-DCMAKE_BUILD_TYPE=Release)")
    endif()
```
However,  in `conan_cmake_detect_vs_runtime`  only checks against `CMAKE_BUILD_TYPE` and not `ARGUMENTS_BUILD_TYPE` so it fails to detect the runtime correctly, and therefore causes the script to fail:
```
    string(TOUPPER ${CMAKE_BUILD_TYPE} build_type)
    set(variables CMAKE_CXX_FLAGS_${build_type} CMAKE_C_FLAGS_${build_type} CMAKE_CXX_FLAGS CMAKE_C_FLAGS)
```

**Comment by akalali** [comment]
How does it fail?

I'm currently trying out several approaches for different build types and what I noticed is that it isn't working if `BUILD_TYPE` is different to `CMAKE_BUILD_TYPE` (see #205).
However, what value is passed for `BUILD_TYPE`? In my scenario everything works fine if I use `BUILD_TYPE ${CMAKE_BUILD_TYPE}`.

**Comment by czoido** [comment]
Hi @L-M-V , @akalali 
Yes, there was an issue when setting `BUILD_TYPE` argument in `conan_cmake_run`  the build failed if not `CMAKE_BUILD_TYPE `argument was provided in the command line.
I have opened a PR that should fix that: https://github.com/conan-io/cmake-conan/pull/209
Thanks a lot for reporting.
