### ISSUE TITLE
if BUILD_TYPE is specified, cmake generator should be used instead of cmake_multi

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/cmake-conan#96]
If the user has overridden the default `BUILD_TYPE`, script currently uses `cmake_multi` generator and two times installs the requested `build_type`, which then generates `cmake` configuration error because another `build_type` is missing (i.e. if the user has selected `Debug` build type, the user wants to use it in all configurations within its IDE and CMake throws error that `cmakebuildinfo_release.cmake` is missing).

[Here](https://github.com/microblink/conan-build-helper/blob/master/mb_conan_build.cmake#L136) is my dirty workaround for that issue from wrapper script that invokes your and performs additional setup specific for our internal build system.

**Comment by memsharded** [comment]
Hi @DoDoENT 

Thanks for reporting, certainly seems a bug. Will try to fix it when possible (might take a couple of weeks). But if you know how to fix it in the conan.cmake script already, please submit a fix, and I'll review and merge it if ok. Many thanks!
